import { defineConfig, devices } from '@playwright/test';

const baseURL = process.env.ZW_E2E_BASE_URL ?? 'http://127.0.0.1:8800';

export default defineConfig({
  testDir: './tests/e2e',
  testMatch: [
    'security_headers_csp.spec.ts',
    'webui_smoke.spec.ts',
    'b11_compliance.spec.ts',
    'b12_intake.spec.ts',
    'nl_accelerator_live.spec.ts',
    'p5_b12_unlock.spec.ts',
    'j1_objection_browser.spec.ts',
    'j1_supply_demand_browser.spec.ts',
    'j1_catalog_drilldown.spec.ts',
    'j1_data_gap.spec.ts',
    'p4_delivery_detail.spec.ts',
    'p5_duplicate_warnings.spec.ts',
    'twin_browser_pages.spec.ts',
    'scenario_agents_ui.spec.ts',
    'trial_shell_experience.spec.ts',
    'customer_acceptance_checklist.spec.ts',
    'b12_iam_governance.spec.ts',
    'permission_invisibility.spec.ts',
    'resource_schema_view.spec.ts',
    'j1_credential_revoke_monitoring.spec.ts',
    'ops_invocation_visibility.spec.ts',
    'national_channel.spec.ts',
    'draft_request_closure.spec.ts',
    'workbench_todo_closure.spec.ts',
    'r12_rendered_language.spec.ts',
    'typed_resource_detail.spec.ts',
    'role_projection_views.spec.ts',
    'perf_loading.spec.ts',
    'form_autofill.spec.ts',
    'wave15_two_stage_walkthrough.spec.ts',
    'permission_matrix_walkthrough.spec.ts',
    'p0_feedback_0611_chain.spec.ts',
    'b2_field_metadata_10col.spec.ts',
    'd57_permission_batch.spec.ts',
    'dept_isolation_two_account.spec.ts',
  ],
  fullyParallel: false,
  workers: 1,
  retries: process.env.CI ? 1 : 0,
  timeout: 60_000,
  expect: { timeout: 15_000 },
  reporter: process.env.CI ? [['github'], ['list']] : [['list']],
  use: {
    baseURL,
    headless: process.env.ZW_E2E_HEADLESS !== '0',
    trace: 'on-first-retry',
    viewport: { width: 1440, height: 1024 },
    ignoreHTTPSErrors: true,
    launchOptions: {
      args: ['--no-proxy-server'],
    },
  },
  projects: [{ name: 'chromium', use: { ...devices['Desktop Chrome'] } }],
});
