"""customer-core-v1 audit-only-skip manifest.

Canonical migration governance rule:

- *_copy1 suffix (e.g. dc_resource_base_info_copy1, data_catalog_copy1, pub_apps_copy1)
  is a DBA history-snapshot shadow table — reason=`legacy_db_history_copy`.
- batch_step_* shares Spring Batch metadata semantics with batch_job_* —
  reason=`spring_batch_metadata`.
- Anything listed here is audit-only: import emits one
  `legacy_object_mapping(canonical_type='legacy_only_evidence')` row plus an
  `audit_event(kind='legacy.coverage.skip')` receipt; the source rows do **not**
  enter business canonical tables (catalog_entry/catalog_item/resource_asset/...).
- Only explicit (schema, table, reason) triples are tolerated; profile must NOT
  use wildcards.  Adding a row is a deliberate audit-only declaration with reason.

Keep this manifest in sync with the source dumps under profile customer-core-v1.
If a real customer dump contains a previously-unseen table, the acceptance flow
fail-closes; the operator must classify and append a row here before re-running.
"""
from __future__ import annotations

AUDIT_ONLY_SKIP_ENTRIES: list[dict[str, str]] = [
    # ---- dsp_bsp ----
    {"schema": "dsp_bsp", "table": "base_dict", "reason": "bsp_static_dictionary"},
    # pub_dict 已提升为真导入（GovernanceMapper._map_dict → dict_projection），
    # 作枚举字段确定性带出 options 真源；不再 audit-only-skip。
    {"schema": "dsp_bsp", "table": "pub_config", "reason": "bsp_static_dictionary"},
    {"schema": "dsp_bsp", "table": "pub_holiday", "reason": "bsp_static_dictionary"},
    {"schema": "dsp_bsp", "table": "pub_icon", "reason": "bsp_static_dictionary"},
    {"schema": "dsp_bsp", "table": "pub_post", "reason": "bsp_static_dictionary"},
    {"schema": "dsp_bsp", "table": "flyway_schema_history", "reason": "flyway_migration_history"},
    {"schema": "dsp_bsp", "table": "pub_app_dict", "reason": "bsp_application_registry"},
    {"schema": "dsp_bsp", "table": "pub_app_group", "reason": "bsp_application_registry"},
    {"schema": "dsp_bsp", "table": "pub_app_help", "reason": "bsp_application_registry"},
    {"schema": "dsp_bsp", "table": "pub_app_role", "reason": "bsp_application_registry"},
    {"schema": "dsp_bsp", "table": "pub_app_role_copy1", "reason": "bsp_application_registry"},
    {"schema": "dsp_bsp", "table": "pub_app_type", "reason": "bsp_application_registry"},
    {"schema": "dsp_bsp", "table": "pub_apps", "reason": "bsp_application_registry"},
    {"schema": "dsp_bsp", "table": "pub_apps_copy1", "reason": "bsp_application_registry"},
    {"schema": "dsp_bsp", "table": "pub_flow", "reason": "bsp_workflow_definition"},
    {"schema": "dsp_bsp", "table": "pub_flow_node", "reason": "bsp_workflow_definition"},
    {"schema": "dsp_bsp", "table": "pub_organ_history", "reason": "bsp_organ_projection"},
    {"schema": "dsp_bsp", "table": "pub_organ_map", "reason": "bsp_organ_projection"},
    {"schema": "dsp_bsp", "table": "pub_organ_of_view", "reason": "bsp_organ_projection"},
    {"schema": "dsp_bsp", "table": "pub_organ_tree", "reason": "bsp_organ_projection"},
    {"schema": "dsp_bsp", "table": "pub_organ_type", "reason": "bsp_organ_projection"},
    {"schema": "dsp_bsp", "table": "pub_organ_view", "reason": "bsp_organ_projection"},
    {"schema": "dsp_bsp", "table": "pub_resource", "reason": "bsp_resource_role_acl"},
    {"schema": "dsp_bsp", "table": "pub_resource_copy1", "reason": "bsp_resource_role_acl"},
    {"schema": "dsp_bsp", "table": "pub_resource_hlj", "reason": "bsp_resource_role_acl"},
    {"schema": "dsp_bsp", "table": "pub_role_copy1", "reason": "bsp_resource_role_acl"},
    {"schema": "dsp_bsp", "table": "pub_role_resource", "reason": "bsp_resource_role_acl"},
    {"schema": "dsp_bsp", "table": "pub_role_resource_copy1", "reason": "bsp_resource_role_acl"},
    {"schema": "dsp_bsp", "table": "pub_user_data_auth_org", "reason": "bsp_user_session_or_audit"},
    {"schema": "dsp_bsp", "table": "pub_user_data_auth_region", "reason": "bsp_user_session_or_audit"},
    {"schema": "dsp_bsp", "table": "pub_user_follow", "reason": "bsp_user_session_or_audit"},
    {"schema": "dsp_bsp", "table": "pub_user_history", "reason": "bsp_user_session_or_audit"},
    {"schema": "dsp_bsp", "table": "pub_user_lock", "reason": "bsp_user_session_or_audit"},
    {"schema": "dsp_bsp", "table": "pub_user_login", "reason": "bsp_user_session_or_audit"},
    {"schema": "dsp_bsp", "table": "pub_user_map", "reason": "bsp_user_session_or_audit"},
    {"schema": "dsp_bsp", "table": "pub_user_operation_log", "reason": "bsp_user_session_or_audit"},
    {"schema": "dsp_bsp", "table": "pub_user_organ_role", "reason": "bsp_user_session_or_audit"},
    {"schema": "dsp_bsp", "table": "pub_user_role", "reason": "bsp_user_session_or_audit"},
    {"schema": "dsp_bsp", "table": "pub_user_role_copy1", "reason": "bsp_user_session_or_audit"},
    {"schema": "dsp_bsp", "table": "pub_user_token", "reason": "bsp_user_session_or_audit"},
    {"schema": "dsp_bsp", "table": "pub_user_type", "reason": "bsp_user_session_or_audit"},
    {"schema": "dsp_bsp", "table": "webfinal_audit_log", "reason": "bsp_legacy_audit_log"},
    {"schema": "dsp_bsp", "table": "xxl_job_user", "reason": "xxl_job_metadata"},
    # ---- dsp_catalog ----
    {"schema": "dsp_catalog", "table": "analysis_catalog_resource", "reason": "catalog_runtime_dictionary"},
    {"schema": "dsp_catalog", "table": "base_message_info", "reason": "catalog_runtime_dictionary"},
    {"schema": "dsp_catalog", "table": "base_system_info", "reason": "catalog_runtime_dictionary"},
    {"schema": "dsp_catalog", "table": "base_tag_relaction_type", "reason": "catalog_runtime_dictionary"},
    {"schema": "dsp_catalog", "table": "base_taginfo_group", "reason": "catalog_runtime_dictionary"},
    {"schema": "dsp_catalog", "table": "basesubject_info", "reason": "catalog_runtime_dictionary"},
    {"schema": "dsp_catalog", "table": "basic_catalog_complie_statistic", "reason": "operational_statistic_projection"},
    {"schema": "dsp_catalog", "table": "data_apply_statistics", "reason": "operational_statistic_projection"},
    {"schema": "dsp_catalog", "table": "data_catalog_dept_group_statistics_temp", "reason": "operational_statistic_projection"},
    {"schema": "dsp_catalog", "table": "data_catalog_group_statistics", "reason": "operational_statistic_projection"},
    {"schema": "dsp_catalog", "table": "data_catalog_relation_statistics", "reason": "operational_statistic_projection"},
    {"schema": "dsp_catalog", "table": "data_catalog_relation_statistics_copy1", "reason": "operational_statistic_projection"},
    {"schema": "dsp_catalog", "table": "data_catalog_theme_group_statistics_temp", "reason": "operational_statistic_projection"},
    {"schema": "dsp_catalog", "table": "data_organization_statistics", "reason": "operational_statistic_projection"},
    {"schema": "dsp_catalog", "table": "data_resource_general_statistics", "reason": "operational_statistic_projection"},
    {"schema": "dsp_catalog", "table": "data_resource_review_statistics", "reason": "operational_statistic_projection"},
    {"schema": "dsp_catalog", "table": "data_resource_statistics", "reason": "operational_statistic_projection"},
    {"schema": "dsp_catalog", "table": "statistic_catalog_compile", "reason": "operational_statistic_projection"},
    {"schema": "dsp_catalog", "table": "catalog_quality_rule", "reason": "catalog_quality_projection"},
    {"schema": "dsp_catalog", "table": "catalog_quality_task_log", "reason": "catalog_quality_projection"},
    {"schema": "dsp_catalog", "table": "catalog_quality_task_result", "reason": "catalog_quality_projection"},
    {"schema": "dsp_catalog", "table": "catalog_quality_template", "reason": "catalog_quality_projection"},
    {"schema": "dsp_catalog", "table": "data_alert_history", "reason": "legacy_apply_history_satellite"},
    {"schema": "dsp_catalog", "table": "data_apply_change", "reason": "legacy_apply_history_satellite"},
    {"schema": "dsp_catalog", "table": "data_apply_column", "reason": "legacy_apply_history_satellite"},
    {"schema": "dsp_catalog", "table": "data_apply_dept_approve", "reason": "legacy_apply_history_satellite"},
    {"schema": "dsp_catalog", "table": "data_apply_report", "reason": "legacy_apply_history_satellite"},
    {"schema": "dsp_catalog", "table": "data_apply_review", "reason": "legacy_apply_history_satellite"},
    {"schema": "dsp_catalog", "table": "data_apply_task", "reason": "legacy_apply_history_satellite"},
    {"schema": "dsp_catalog", "table": "data_catalog_approve", "reason": "legacy_catalog_history_satellite"},
    {"schema": "dsp_catalog", "table": "data_catalog_category", "reason": "legacy_catalog_history_satellite"},
    {"schema": "dsp_catalog", "table": "data_catalog_category_copy1", "reason": "legacy_catalog_history_satellite"},
    {"schema": "dsp_catalog", "table": "data_catalog_column_20241126", "reason": "legacy_catalog_history_satellite"},
    {"schema": "dsp_catalog", "table": "data_catalog_column_copy1", "reason": "legacy_catalog_history_satellite"},
    {"schema": "dsp_catalog", "table": "data_catalog_column_extend_field", "reason": "legacy_catalog_history_satellite"},
    {"schema": "dsp_catalog", "table": "data_catalog_column_version", "reason": "legacy_catalog_history_satellite"},
    {"schema": "dsp_catalog", "table": "data_catalog_copy1", "reason": "legacy_catalog_history_satellite"},
    {"schema": "dsp_catalog", "table": "data_catalog_copy2", "reason": "legacy_catalog_history_satellite"},
    {"schema": "dsp_catalog", "table": "data_catalog_duty_link", "reason": "legacy_catalog_history_satellite"},
    {"schema": "dsp_catalog", "table": "data_catalog_dutylist", "reason": "legacy_catalog_history_satellite"},
    {"schema": "dsp_catalog", "table": "data_catalog_export", "reason": "legacy_catalog_history_satellite"},
    {"schema": "dsp_catalog", "table": "data_catalog_group_lk", "reason": "legacy_catalog_history_satellite"},
    {"schema": "dsp_catalog", "table": "data_catalog_import", "reason": "legacy_catalog_history_satellite"},
    {"schema": "dsp_catalog", "table": "data_catalog_open_extend", "reason": "legacy_catalog_history_satellite"},
    {"schema": "dsp_catalog", "table": "data_catalog_trans_group", "reason": "legacy_catalog_history_satellite"},
    {"schema": "dsp_catalog", "table": "data_catalog_version", "reason": "legacy_catalog_history_satellite"},
    {"schema": "dsp_catalog", "table": "data_comment_info", "reason": "portal_feedback_dictionary"},
    {"schema": "dsp_catalog", "table": "data_feedback_info", "reason": "portal_feedback_dictionary"},
    {"schema": "dsp_catalog", "table": "data_recommend", "reason": "portal_feedback_dictionary"},
    {"schema": "dsp_catalog", "table": "data_recommend_approve", "reason": "portal_feedback_dictionary"},
    {"schema": "dsp_catalog", "table": "data_score", "reason": "portal_feedback_dictionary"},
    {"schema": "dsp_catalog", "table": "data_score_record", "reason": "portal_feedback_dictionary"},
    {"schema": "dsp_catalog", "table": "news_column", "reason": "portal_feedback_dictionary"},
    {"schema": "dsp_catalog", "table": "news_resource", "reason": "portal_feedback_dictionary"},
    {"schema": "dsp_catalog", "table": "data_ext_elem_catalog_compile_task", "reason": "ext_elem_compile_task_projection"},
    {"schema": "dsp_catalog", "table": "data_ext_elem_catalog_compile_task_objection", "reason": "ext_elem_compile_task_projection"},
    {"schema": "dsp_catalog", "table": "data_ext_elem_catalog_item_compile_task", "reason": "ext_elem_compile_task_projection"},
    {"schema": "dsp_catalog", "table": "data_history_catalog_deal", "reason": "legacy_catalog_deal_history"},
    {"schema": "dsp_catalog", "table": "data_history_catalog_deal_approve", "reason": "legacy_catalog_deal_history"},
    {"schema": "dsp_catalog", "table": "data_import_template", "reason": "catalog_import_template_dictionary"},
    {"schema": "dsp_catalog", "table": "data_item_info", "reason": "catalog_import_template_dictionary"},
    {"schema": "dsp_catalog", "table": "data_layout", "reason": "catalog_import_template_dictionary"},
    {"schema": "dsp_catalog", "table": "data_resource_api", "reason": "legacy_resource_satellite_redundant_with_metaresource"},
    {"schema": "dsp_catalog", "table": "data_resource_file", "reason": "legacy_resource_satellite_redundant_with_metaresource"},
    {"schema": "dsp_catalog", "table": "data_resource_table", "reason": "legacy_resource_satellite_redundant_with_metaresource"},
    {"schema": "dsp_catalog", "table": "data_resource_table_column", "reason": "legacy_resource_satellite_redundant_with_metaresource"},
    {"schema": "dsp_catalog", "table": "data_source_catalog_lk", "reason": "legacy_data_source_join"},
    {"schema": "dsp_catalog", "table": "data_source_column_lk", "reason": "legacy_data_source_join"},
    {"schema": "dsp_catalog", "table": "flyway_manage_history", "reason": "flyway_migration_history"},
    {"schema": "dsp_catalog", "table": "flyway_schema_history", "reason": "flyway_migration_history"},
    {"schema": "dsp_catalog", "table": "flyway_schema_history_apply", "reason": "flyway_migration_history"},
    {"schema": "dsp_catalog", "table": "model_catalog_column_properties", "reason": "catalog_model_template_dictionary"},
    {"schema": "dsp_catalog", "table": "model_catalog_properties", "reason": "catalog_model_template_dictionary"},
    {"schema": "dsp_catalog", "table": "model_catalog_step", "reason": "catalog_model_template_dictionary"},
    {"schema": "dsp_catalog", "table": "model_catalog_template", "reason": "catalog_model_template_dictionary"},
    {"schema": "dsp_catalog", "table": "model_dimension", "reason": "catalog_model_template_dictionary"},
    {"schema": "dsp_catalog", "table": "model_properties", "reason": "catalog_model_template_dictionary"},
    {"schema": "dsp_catalog", "table": "model_property_group", "reason": "catalog_model_template_dictionary"},
    {"schema": "dsp_catalog", "table": "open_catalog_group", "reason": "p7_projection_pending"},
    {"schema": "dsp_catalog", "table": "open_catalog_group_link", "reason": "p7_projection_pending"},
    {"schema": "dsp_catalog", "table": "open_catalog_group_type", "reason": "p7_projection_pending"},
    {"schema": "dsp_catalog", "table": "push_open_catalog", "reason": "p7_projection_pending"},
    {"schema": "dsp_catalog", "table": "os_currentstep", "reason": "osworkflow_runtime"},
    {"schema": "dsp_catalog", "table": "os_currentstep_prev", "reason": "osworkflow_runtime"},
    {"schema": "dsp_catalog", "table": "os_entryids", "reason": "osworkflow_runtime"},
    {"schema": "dsp_catalog", "table": "os_historystep", "reason": "osworkflow_runtime"},
    {"schema": "dsp_catalog", "table": "os_historystep_prev", "reason": "osworkflow_runtime"},
    {"schema": "dsp_catalog", "table": "os_stepids", "reason": "osworkflow_runtime"},
    {"schema": "dsp_catalog", "table": "os_wfentry", "reason": "osworkflow_runtime"},
    {"schema": "dsp_catalog", "table": "up_task_directory", "reason": "up_task_projection"},
    {"schema": "dsp_catalog", "table": "up_task_general_basic", "reason": "up_task_projection"},
    {"schema": "dsp_catalog", "table": "up_task_general_basic_ls", "reason": "up_task_projection"},
    {"schema": "dsp_catalog", "table": "user_operation_log", "reason": "operation_log_audit"},
    # ---- dsp_metaresource ----
    {"schema": "dsp_metaresource", "table": "audit_todo_task", "reason": "metadata_audit_todo"},
    {"schema": "dsp_metaresource", "table": "database_manage_history", "reason": "metadata_database_history"},
    {"schema": "dsp_metaresource", "table": "db_meta_column_history", "reason": "metadata_runtime_db_snapshot"},
    {"schema": "dsp_metaresource", "table": "db_meta_database", "reason": "metadata_runtime_db_snapshot"},
    {"schema": "dsp_metaresource", "table": "db_meta_database_history", "reason": "metadata_runtime_db_snapshot"},
    {"schema": "dsp_metaresource", "table": "db_meta_database_permission", "reason": "metadata_runtime_db_snapshot"},
    {"schema": "dsp_metaresource", "table": "db_meta_foreignkey", "reason": "metadata_runtime_db_snapshot"},
    {"schema": "dsp_metaresource", "table": "db_meta_index", "reason": "metadata_runtime_db_snapshot"},
    {"schema": "dsp_metaresource", "table": "db_meta_index_history", "reason": "metadata_runtime_db_snapshot"},
    {"schema": "dsp_metaresource", "table": "db_meta_table_data_num", "reason": "metadata_runtime_db_snapshot"},
    {"schema": "dsp_metaresource", "table": "db_meta_table_history", "reason": "metadata_runtime_db_snapshot"},
    {"schema": "dsp_metaresource", "table": "file_server", "reason": "metadata_file_server_registry"},
    {"schema": "dsp_metaresource", "table": "file_server_history", "reason": "metadata_file_server_registry"},
    {"schema": "dsp_metaresource", "table": "flyway_schema_history", "reason": "flyway_migration_history"},
    {"schema": "dsp_metaresource", "table": "meta_data_center_area", "reason": "metadata_static_dictionary"},
    {"schema": "dsp_metaresource", "table": "meta_model_info", "reason": "metadata_static_dictionary"},
    {"schema": "dsp_metaresource", "table": "rc_resource_export", "reason": "metadata_export_log"},
    {"schema": "dsp_metaresource", "table": "resource_standard_changes", "reason": "metadata_standard_change_history"},
    {"schema": "dsp_metaresource", "table": "system_push_data_log", "reason": "metadata_push_audit_log"},
    # ---- dsp_require ----
    {"schema": "dsp_require", "table": "data_business", "reason": "require_satellite_or_statistic_projection"},
    {"schema": "dsp_require", "table": "data_business_approve", "reason": "require_satellite_or_statistic_projection"},
    {"schema": "dsp_require", "table": "data_connect_original_require", "reason": "require_satellite_or_statistic_projection"},
    {"schema": "dsp_require", "table": "data_connect_original_require_link", "reason": "require_satellite_or_statistic_projection"},
    {"schema": "dsp_require", "table": "data_connect_original_require_process", "reason": "require_satellite_or_statistic_projection"},
    {"schema": "dsp_require", "table": "data_item", "reason": "require_satellite_or_statistic_projection"},
    {"schema": "dsp_require", "table": "data_message", "reason": "require_satellite_or_statistic_projection"},
    {"schema": "dsp_require", "table": "data_org_review_statistics", "reason": "require_satellite_or_statistic_projection"},
    {"schema": "dsp_require", "table": "data_original_require_approve", "reason": "require_satellite_or_statistic_projection"},
    {"schema": "dsp_require", "table": "data_original_require_column", "reason": "require_satellite_or_statistic_projection"},
    {"schema": "dsp_require", "table": "data_original_require_link", "reason": "require_satellite_or_statistic_projection"},
    {"schema": "dsp_require", "table": "data_original_require_resource", "reason": "require_satellite_or_statistic_projection"},
    {"schema": "dsp_require", "table": "data_require_approve", "reason": "require_satellite_or_statistic_projection"},
    {"schema": "dsp_require", "table": "data_require_column", "reason": "require_satellite_or_statistic_projection"},
    {"schema": "dsp_require", "table": "data_require_org_statistics", "reason": "require_satellite_or_statistic_projection"},
    {"schema": "dsp_require", "table": "data_require_resolve_link", "reason": "require_satellite_or_statistic_projection"},
    {"schema": "dsp_require", "table": "data_require_resource", "reason": "require_satellite_or_statistic_projection"},
    {"schema": "dsp_require", "table": "data_require_review", "reason": "require_satellite_or_statistic_projection"},
    {"schema": "dsp_require", "table": "data_require_task_link", "reason": "require_satellite_or_statistic_projection"},
    {"schema": "dsp_require", "table": "data_resource_review_statistics", "reason": "require_satellite_or_statistic_projection"},
    {"schema": "dsp_require", "table": "data_subtask", "reason": "require_satellite_or_statistic_projection"},
    {"schema": "dsp_require", "table": "data_task", "reason": "require_satellite_or_statistic_projection"},
    {"schema": "dsp_require", "table": "data_task_process", "reason": "require_satellite_or_statistic_projection"},
    {"schema": "dsp_require", "table": "data_taskitem_link", "reason": "require_satellite_or_statistic_projection"},
    {"schema": "dsp_require", "table": "flyway_schema_history", "reason": "flyway_migration_history"},
    # ---- dsp_handling ----
    {"schema": "dsp_handling", "table": "data_message_info", "reason": "handling_message_audit"},
    {"schema": "dsp_handling", "table": "flyway_schema_history", "reason": "flyway_migration_history"},
    # ---- dsp_example ----
    {"schema": "dsp_example", "table": "data_example_push_link", "reason": "topic_package_push_audit"},
    {"schema": "dsp_example", "table": "flyway_schema_history", "reason": "flyway_migration_history"},
    # ---- dsp_connect ----
    {"schema": "dsp_connect", "table": "batch_job_execution", "reason": "spring_batch_metadata"},
    {"schema": "dsp_connect", "table": "batch_job_execution_context", "reason": "spring_batch_metadata"},
    {"schema": "dsp_connect", "table": "batch_job_execution_params", "reason": "spring_batch_metadata"},
    {"schema": "dsp_connect", "table": "batch_job_execution_seq", "reason": "spring_batch_metadata"},
    {"schema": "dsp_connect", "table": "batch_job_instance", "reason": "spring_batch_metadata"},
    {"schema": "dsp_connect", "table": "batch_job_seq", "reason": "spring_batch_metadata"},
    {"schema": "dsp_connect", "table": "batch_step_execution", "reason": "spring_batch_metadata"},
    {"schema": "dsp_connect", "table": "batch_step_execution_context", "reason": "spring_batch_metadata"},
    {"schema": "dsp_connect", "table": "batch_step_execution_seq", "reason": "spring_batch_metadata"},
    {"schema": "dsp_connect", "table": "dc_datasource", "reason": "external_datasource_secret_excluded"},
    {"schema": "dsp_connect", "table": "dc_resource_base_info_copy1", "reason": "legacy_db_history_copy"},
    {"schema": "dsp_connect", "table": "flyway_schema_history", "reason": "flyway_migration_history"},
    # ---- dsp_service ----
    {"schema": "dsp_service", "table": "api_access_ip", "reason": "api_runtime_satellite"},
    {"schema": "dsp_service", "table": "api_check_info", "reason": "api_runtime_satellite"},
    {"schema": "dsp_service", "table": "api_group_lk", "reason": "api_runtime_satellite"},
    {"schema": "dsp_service", "table": "api_service_counter", "reason": "api_runtime_satellite"},
    {"schema": "dsp_service", "table": "api_service_errors", "reason": "api_runtime_satellite"},
    {"schema": "dsp_service", "table": "api_service_filter", "reason": "api_runtime_satellite"},
    {"schema": "dsp_service", "table": "api_service_fuse", "reason": "api_runtime_satellite"},
    {"schema": "dsp_service", "table": "api_service_pool", "reason": "api_runtime_satellite"},
    {"schema": "dsp_service", "table": "app_base_info", "reason": "api_app_baseinfo_registry"},
    {"schema": "dsp_service", "table": "flyway_schema_history", "reason": "flyway_migration_history"},
    # ---- dsp_pipelines ----
    {"schema": "dsp_pipelines", "table": "acct_table_job", "reason": "pipelines_runtime_evidence"},
    {"schema": "dsp_pipelines", "table": "convert_db_type", "reason": "pipelines_runtime_evidence"},
    {"schema": "dsp_pipelines", "table": "db_js_text", "reason": "pipelines_runtime_evidence"},
    {"schema": "dsp_pipelines", "table": "exception_messages", "reason": "pipelines_runtime_evidence"},
    {"schema": "dsp_pipelines", "table": "exchange_etl_type", "reason": "pipelines_runtime_evidence"},
    {"schema": "dsp_pipelines", "table": "exchange_executor", "reason": "pipelines_runtime_evidence"},
    {"schema": "dsp_pipelines", "table": "exchange_file_log", "reason": "pipelines_runtime_evidence"},
    {"schema": "dsp_pipelines", "table": "exchange_node", "reason": "pipelines_runtime_evidence"},
    {"schema": "dsp_pipelines", "table": "exchange_pipelines", "reason": "pipelines_runtime_evidence"},
    {"schema": "dsp_pipelines", "table": "exchange_pipelines_database", "reason": "pipelines_runtime_evidence"},
    {"schema": "dsp_pipelines", "table": "exchange_pipelines_database_copy1", "reason": "pipelines_runtime_evidence"},
    {"schema": "dsp_pipelines", "table": "exchange_pipelines_subscribe", "reason": "pipelines_runtime_evidence"},
    {"schema": "dsp_pipelines", "table": "exchange_rule", "reason": "pipelines_runtime_evidence"},
    {"schema": "dsp_pipelines", "table": "meta_database", "reason": "pipelines_runtime_evidence"},
    {"schema": "dsp_pipelines", "table": "meta_database_feature", "reason": "pipelines_runtime_evidence"},
    {"schema": "dsp_pipelines", "table": "meta_host", "reason": "pipelines_runtime_evidence"},
    {"schema": "dsp_pipelines", "table": "nifi_job_history", "reason": "pipelines_runtime_evidence"},
    {"schema": "dsp_pipelines", "table": "probe_task", "reason": "pipelines_runtime_evidence"},
    {"schema": "dsp_pipelines", "table": "probe_task_column_rule", "reason": "pipelines_runtime_evidence"},
    {"schema": "dsp_pipelines", "table": "probe_task_column_rule_result", "reason": "pipelines_runtime_evidence"},
    {"schema": "dsp_pipelines", "table": "probe_task_result", "reason": "pipelines_runtime_evidence"},
    {"schema": "dsp_pipelines", "table": "resource_applied", "reason": "pipelines_runtime_evidence"},
    {"schema": "dsp_pipelines", "table": "resource_applied_cancelled", "reason": "pipelines_runtime_evidence"},
    {"schema": "dsp_pipelines", "table": "resource_change_log", "reason": "pipelines_runtime_evidence"},
    {"schema": "dsp_pipelines", "table": "resource_file_download_log", "reason": "pipelines_runtime_evidence"},
    {"schema": "dsp_pipelines", "table": "resource_lock", "reason": "pipelines_runtime_evidence"},
    {"schema": "dsp_pipelines", "table": "resource_status", "reason": "pipelines_runtime_evidence"},
    {"schema": "dsp_pipelines", "table": "statisc_subscribe_job", "reason": "pipelines_runtime_evidence"},
    {"schema": "dsp_pipelines", "table": "subscribe_detail", "reason": "pipelines_runtime_evidence"},
    {"schema": "dsp_pipelines", "table": "subscribe_detail_file", "reason": "pipelines_runtime_evidence"},
    {"schema": "dsp_pipelines", "table": "subscribe_job", "reason": "pipelines_runtime_evidence"},
    {"schema": "dsp_pipelines", "table": "warning_dictionary", "reason": "pipelines_runtime_evidence"},
    {"schema": "dsp_pipelines", "table": "flyway_schema_history", "reason": "flyway_migration_history"},
    # ---- dsp_monitor ----
    {"schema": "dsp_monitor", "table": "automonitor_group", "reason": "monitor_runtime_evidence"},
    {"schema": "dsp_monitor", "table": "automonitor_item", "reason": "monitor_runtime_evidence"},
    {"schema": "dsp_monitor", "table": "knowledge_audit", "reason": "monitor_runtime_evidence"},
    {"schema": "dsp_monitor", "table": "knowledge_manage", "reason": "monitor_runtime_evidence"},
    {"schema": "dsp_monitor", "table": "manual_inspection_plan", "reason": "monitor_runtime_evidence"},
    {"schema": "dsp_monitor", "table": "matter_classify_manage", "reason": "monitor_runtime_evidence"},
    {"schema": "dsp_monitor", "table": "monitor_filled_result", "reason": "monitor_runtime_evidence"},
    {"schema": "dsp_monitor", "table": "monitor_warning", "reason": "monitor_runtime_evidence"},
    {"schema": "dsp_monitor", "table": "product_service_config", "reason": "monitor_runtime_evidence"},
    {"schema": "dsp_monitor", "table": "product_service_warning_rule", "reason": "monitor_runtime_evidence"},
    {"schema": "dsp_monitor", "table": "product_task_config", "reason": "monitor_runtime_evidence"},
    {"schema": "dsp_monitor", "table": "scheduling_audit", "reason": "monitor_runtime_evidence"},
    {"schema": "dsp_monitor", "table": "scheduling_detail", "reason": "monitor_runtime_evidence"},
    {"schema": "dsp_monitor", "table": "service_warning_rule", "reason": "monitor_runtime_evidence"},
    {"schema": "dsp_monitor", "table": "flyway_schema_history", "reason": "flyway_migration_history"},
    # ---- dsp_perform ----
    {"schema": "dsp_perform", "table": "analysis_catalog_resource", "reason": "perform_static_projection"},
    {"schema": "dsp_perform", "table": "flyway_perform_history", "reason": "flyway_migration_history"},
    {"schema": "dsp_perform", "table": "kpi_data_script", "reason": "kpi_projection_runtime"},
    {"schema": "dsp_perform", "table": "kpi_index_calculation_param", "reason": "kpi_projection_runtime"},
    {"schema": "dsp_perform", "table": "kpi_index_calculation_rule", "reason": "kpi_projection_runtime"},
    {"schema": "dsp_perform", "table": "kpi_index_model", "reason": "kpi_projection_runtime"},
    {"schema": "dsp_perform", "table": "kpi_index_result", "reason": "kpi_projection_runtime"},
    {"schema": "dsp_perform", "table": "kpi_index_rule", "reason": "kpi_projection_runtime"},
    {"schema": "dsp_perform", "table": "kpi_index_system", "reason": "kpi_projection_runtime"},
    {"schema": "dsp_perform", "table": "kpi_pdf_report", "reason": "kpi_projection_runtime"},
    {"schema": "dsp_perform", "table": "sys_plan", "reason": "perform_plan_runtime"},
    {"schema": "dsp_perform", "table": "sys_plan_monitor", "reason": "perform_plan_runtime"},
]


def audit_only_skip_for(schema: str) -> dict[str, str]:
    """Return {table: reason} for the given schema (empty dict if schema unknown)."""
    return {entry["table"]: entry["reason"] for entry in AUDIT_ONLY_SKIP_ENTRIES if entry["schema"] == schema}


def is_audit_only_skip(schema: str, table: str) -> bool:
    return any(entry["schema"] == schema and entry["table"] == table for entry in AUDIT_ONLY_SKIP_ENTRIES)
