/* AUTO-GENERATED by scripts/export_agent_contract.py — DO NOT EDIT BY HAND.
 * Regenerate via: python3 scripts/export_agent_contract.py
 * Source of truth: zw_brain/capability_registry/registered/*.json
 * 派生规则：skill_id 点号前缀 → WEBUI_PAGE_PREFIX_MAP（脚本内）。
 */

export interface PageCapabilityEntry {
  skillId: string;
  mode: 'read' | 'write';
  auditClass: string;
  humanConfirmationRequired: boolean;
  roles: string[];
  permissions: string[];
}

export interface PageRegistryEntry {
  anchor: string;
  capabilities: PageCapabilityEntry[];
}

export const PAGE_REGISTRY: PageRegistryEntry[] = [
  { anchor: "P1", capabilities: [
    {"skillId": "system.snapshot", "mode": "read", "auditClass": "read-default", "humanConfirmationRequired": false, "roles": [], "permissions": ["system.snapshot.execute"]},
    {"skillId": "workbench.view", "mode": "read", "auditClass": "read-default", "humanConfirmationRequired": false, "roles": ["ROLE_ORGAN_OPERATER", "ROLE_ORGAN_MANAGER", "ROLE_BUSIAUDIT", "ROLE_SECURITY_AUDIT", "ROLE_SYSTEM"], "permissions": ["workbench.view.execute"]},
  ] },
  { anchor: "P2", capabilities: [
    {"skillId": "catalog.browse", "mode": "read", "auditClass": "read-default", "humanConfirmationRequired": false, "roles": [], "permissions": ["catalog.browse.execute"]},
    {"skillId": "catalog.entry.query", "mode": "read", "auditClass": "read-trace", "humanConfirmationRequired": false, "roles": [], "permissions": ["catalog.entry.query.execute"]},
    {"skillId": "catalog.entry.reverse_draft.suggest", "mode": "read", "auditClass": "read-trace", "humanConfirmationRequired": false, "roles": [], "permissions": ["catalog.entry.reverse_draft.suggest.execute"]},
    {"skillId": "catalog.resource.list", "mode": "read", "auditClass": "read-default", "humanConfirmationRequired": false, "roles": [], "permissions": ["catalog.resource.list.execute"]},
    {"skillId": "catalog.resource_view", "mode": "read", "auditClass": "read-default", "humanConfirmationRequired": false, "roles": [], "permissions": ["catalog.resource_view.execute"]},
    {"skillId": "data.search", "mode": "read", "auditClass": "read-default", "humanConfirmationRequired": false, "roles": [], "permissions": ["data.search.execute"]},
    {"skillId": "metadata.schema.query", "mode": "read", "auditClass": "read-trace", "humanConfirmationRequired": false, "roles": [], "permissions": ["metadata.schema.query.execute"]},
    {"skillId": "catalog.entry.create", "mode": "write", "auditClass": "write-critical", "humanConfirmationRequired": true, "roles": [], "permissions": ["catalog.entry.create.execute"]},
    {"skillId": "catalog.entry.create_draft", "mode": "write", "auditClass": "write-critical", "humanConfirmationRequired": true, "roles": [], "permissions": ["catalog.entry.create_draft.execute"]},
    {"skillId": "catalog.entry.publish", "mode": "write", "auditClass": "write-critical", "humanConfirmationRequired": true, "roles": [], "permissions": ["catalog.entry.publish.execute"]},
    {"skillId": "catalog.entry.reverse_draft.confirm", "mode": "write", "auditClass": "write-critical", "humanConfirmationRequired": true, "roles": [], "permissions": ["catalog.entry.reverse_draft.confirm.execute"]},
    {"skillId": "catalog.entry.reverse_draft.create", "mode": "write", "auditClass": "write-default", "humanConfirmationRequired": true, "roles": [], "permissions": ["catalog.entry.reverse_draft.create.execute"]},
    {"skillId": "catalog.entry.reverse_draft.reject", "mode": "write", "auditClass": "write-default", "humanConfirmationRequired": true, "roles": [], "permissions": ["catalog.entry.reverse_draft.reject.execute"]},
    {"skillId": "catalog.entry.review", "mode": "write", "auditClass": "write-critical", "humanConfirmationRequired": true, "roles": [], "permissions": ["catalog.entry.review.execute"]},
    {"skillId": "catalog.entry.submit_review", "mode": "write", "auditClass": "write-critical", "humanConfirmationRequired": true, "roles": [], "permissions": ["catalog.entry.submit_review.execute"]},
    {"skillId": "catalog.entry.update", "mode": "write", "auditClass": "write-critical", "humanConfirmationRequired": true, "roles": [], "permissions": ["catalog.entry.update.execute"]},
    {"skillId": "catalog.national_ext_elem.compile", "mode": "write", "auditClass": "catalog-write", "humanConfirmationRequired": true, "roles": [], "permissions": ["catalog.national_ext_elem.compile.execute"]},
  ] },
  { anchor: "P3", capabilities: [
    {"skillId": "approval.view", "mode": "read", "auditClass": "read-default", "humanConfirmationRequired": false, "roles": [], "permissions": ["approval.view.execute"]},
    {"skillId": "request.list", "mode": "read", "auditClass": "read-default", "humanConfirmationRequired": false, "roles": [], "permissions": ["request.list.execute"]},
    {"skillId": "application.dept_approve", "mode": "write", "auditClass": "write-critical", "humanConfirmationRequired": true, "roles": [], "permissions": ["application.dept_approve.execute"]},
    {"skillId": "application.draft.suggest", "mode": "write", "auditClass": "read", "humanConfirmationRequired": false, "roles": [], "permissions": ["application.draft.suggest.execute"]},
    {"skillId": "application.escalate_national", "mode": "write", "auditClass": "adapter-write", "humanConfirmationRequired": true, "roles": [], "permissions": ["application.escalate_national.execute"]},
    {"skillId": "application.grant.approve", "mode": "write", "auditClass": "write-critical", "humanConfirmationRequired": true, "roles": [], "permissions": ["application.grant.approve.execute"]},
    {"skillId": "application.grant.revoke", "mode": "write", "auditClass": "write-critical", "humanConfirmationRequired": true, "roles": [], "permissions": ["application.grant.revoke.execute"]},
    {"skillId": "application.grant.suspend", "mode": "write", "auditClass": "write-critical", "humanConfirmationRequired": true, "roles": [], "permissions": ["application.grant.suspend.execute"]},
    {"skillId": "application.platform_approve", "mode": "write", "auditClass": "write-critical", "humanConfirmationRequired": true, "roles": [], "permissions": ["application.platform_approve.execute"]},
    {"skillId": "application.resource.review", "mode": "write", "auditClass": "write-critical", "humanConfirmationRequired": true, "roles": [], "permissions": ["application.resource.review.execute"]},
    {"skillId": "approval.case.decide", "mode": "write", "auditClass": "write-critical", "humanConfirmationRequired": true, "roles": [], "permissions": ["approval.case.decide.execute"]},
    {"skillId": "approval.evidence.summarize", "mode": "write", "auditClass": "read", "humanConfirmationRequired": false, "roles": [], "permissions": ["approval.evidence.summarize.execute"]},
    {"skillId": "request.create", "mode": "write", "auditClass": "write-critical", "humanConfirmationRequired": true, "roles": [], "permissions": ["request.create.execute"]},
    {"skillId": "request.draft.ai_suggest", "mode": "write", "auditClass": "write-default", "humanConfirmationRequired": false, "roles": [], "permissions": ["request.draft.ai_suggest.execute"]},
    {"skillId": "request.field.update", "mode": "write", "auditClass": "write-default", "humanConfirmationRequired": false, "roles": [], "permissions": ["request.field.update.execute"]},
    {"skillId": "request.submit", "mode": "write", "auditClass": "write-critical", "humanConfirmationRequired": true, "roles": [], "permissions": ["request.submit.execute"]},
  ] },
  { anchor: "P4", capabilities: [
    {"skillId": "credential.query", "mode": "read", "auditClass": "read", "humanConfirmationRequired": false, "roles": [], "permissions": ["credential.query.execute"]},
    {"skillId": "delivery.list", "mode": "read", "auditClass": "read-default", "humanConfirmationRequired": false, "roles": [], "permissions": ["delivery.list.execute"]},
    {"skillId": "credential.issue", "mode": "write", "auditClass": "write-critical", "humanConfirmationRequired": false, "roles": [], "permissions": ["credential.issue.execute"]},
    {"skillId": "credential.sample.render", "mode": "write", "auditClass": "read", "humanConfirmationRequired": false, "roles": [], "permissions": ["credential.sample.render.execute"]},
    {"skillId": "delivery.file.download", "mode": "write", "auditClass": "write-default", "humanConfirmationRequired": true, "roles": [], "permissions": ["delivery.file.download.execute"]},
    {"skillId": "delivery.reconcile_receipt", "mode": "write", "auditClass": "write-critical", "humanConfirmationRequired": true, "roles": [], "permissions": ["delivery.reconcile_receipt.execute"]},
    {"skillId": "delivery.trigger_recovery", "mode": "write", "auditClass": "write-critical", "humanConfirmationRequired": true, "roles": [], "permissions": ["delivery.trigger_recovery.execute"]},
  ] },
  { anchor: "P5", capabilities: [
    {"skillId": "resource.asset.query", "mode": "read", "auditClass": "read-trace", "humanConfirmationRequired": false, "roles": [], "permissions": ["resource.asset.query.execute"]},
    {"skillId": "resource.api.publish", "mode": "write", "auditClass": "write-critical", "humanConfirmationRequired": true, "roles": [], "permissions": ["resource.api.publish.execute"]},
    {"skillId": "resource.api.register", "mode": "write", "auditClass": "write-critical", "humanConfirmationRequired": true, "roles": [], "permissions": ["resource.api.register.execute"]},
    {"skillId": "resource.api.review", "mode": "write", "auditClass": "write-critical", "humanConfirmationRequired": true, "roles": [], "permissions": ["resource.api.review.execute"]},
    {"skillId": "resource.api.submit_review", "mode": "write", "auditClass": "write-critical", "humanConfirmationRequired": true, "roles": [], "permissions": ["resource.api.submit_review.execute"]},
    {"skillId": "resource.api.test", "mode": "write", "auditClass": "write-critical", "humanConfirmationRequired": true, "roles": [], "permissions": ["resource.api.test.execute"]},
    {"skillId": "resource.api.withdraw", "mode": "write", "auditClass": "write-critical", "humanConfirmationRequired": true, "roles": [], "permissions": ["resource.api.withdraw.execute"]},
    {"skillId": "resource.asset.publish", "mode": "write", "auditClass": "write-critical", "humanConfirmationRequired": true, "roles": [], "permissions": ["resource.asset.publish.execute"]},
    {"skillId": "resource.asset.review", "mode": "write", "auditClass": "write-critical", "humanConfirmationRequired": true, "roles": [], "permissions": ["resource.asset.review.execute"]},
    {"skillId": "resource.asset.submit_review", "mode": "write", "auditClass": "write-critical", "humanConfirmationRequired": true, "roles": [], "permissions": ["resource.asset.submit_review.execute"]},
    {"skillId": "resource.mount.file.prepare", "mode": "write", "auditClass": "write-critical", "humanConfirmationRequired": true, "roles": [], "permissions": ["resource.mount.file.prepare.execute"]},
    {"skillId": "resource.mount.table.prepare", "mode": "write", "auditClass": "write-critical", "humanConfirmationRequired": true, "roles": [], "permissions": ["resource.mount.table.prepare.execute"]},
    {"skillId": "service.publish_or_suspend", "mode": "write", "auditClass": "write-critical", "humanConfirmationRequired": true, "roles": [], "permissions": ["service.publish_or_suspend.execute"]},
  ] },
  { anchor: "P7", capabilities: [
  ] },
  { anchor: "B1.1", capabilities: [
    {"skillId": "audit.event.accountability", "mode": "read", "auditClass": "read-sensitive", "humanConfirmationRequired": false, "roles": [], "permissions": ["audit.event.accountability.execute"]},
    {"skillId": "audit.event.anomaly", "mode": "read", "auditClass": "read-sensitive", "humanConfirmationRequired": false, "roles": [], "permissions": ["audit.event.anomaly.execute"]},
    {"skillId": "audit.event.query", "mode": "read", "auditClass": "read-sensitive", "humanConfirmationRequired": false, "roles": [], "permissions": ["audit.event.query.execute"]},
    {"skillId": "audit.event.replay", "mode": "read", "auditClass": "read-sensitive", "humanConfirmationRequired": false, "roles": [], "permissions": ["audit.event.replay.execute"]},
    {"skillId": "audit.event.statistics", "mode": "read", "auditClass": "read-sensitive", "humanConfirmationRequired": false, "roles": [], "permissions": ["audit.event.statistics.execute"]},
    {"skillId": "audit.list", "mode": "read", "auditClass": "read-default", "humanConfirmationRequired": false, "roles": [], "permissions": ["audit.list.execute"]},
    {"skillId": "audit.replay_evidence_chain", "mode": "read", "auditClass": "read-sensitive", "humanConfirmationRequired": false, "roles": [], "permissions": ["audit.replay_evidence_chain.execute"]},
    {"skillId": "governance.access_matrix", "mode": "read", "auditClass": "read-sensitive", "humanConfirmationRequired": false, "roles": [], "permissions": ["governance.access_matrix.execute"]},
    {"skillId": "governance.actor.list", "mode": "read", "auditClass": "read-sensitive", "humanConfirmationRequired": false, "roles": [], "permissions": ["governance.actor.list.execute"]},
    {"skillId": "governance.iam_overview", "mode": "read", "auditClass": "read-sensitive", "humanConfirmationRequired": false, "roles": [], "permissions": ["governance.iam_overview.execute"]},
    {"skillId": "governance.policy_candidate.list", "mode": "read", "auditClass": "read-sensitive", "humanConfirmationRequired": false, "roles": [], "permissions": ["governance.policy_candidate.list.execute"]},
    {"skillId": "objection.case.query", "mode": "read", "auditClass": "read-default", "humanConfirmationRequired": false, "roles": [], "permissions": ["objection.case.query.execute"]},
    {"skillId": "ops.service.invocation.query", "mode": "read", "auditClass": "read-default", "humanConfirmationRequired": false, "roles": [], "permissions": ["ops.service.invocation.query.execute"]},
    {"skillId": "ops.service.report.query", "mode": "read", "auditClass": "read-default", "humanConfirmationRequired": false, "roles": [], "permissions": ["ops.service.report.query.execute"]},
    {"skillId": "governance.actor.role.assign", "mode": "write", "auditClass": "write-critical", "humanConfirmationRequired": true, "roles": [], "permissions": ["governance.actor.role.assign.execute"]},
    {"skillId": "governance.actor.role.revoke", "mode": "write", "auditClass": "write-critical", "humanConfirmationRequired": true, "roles": [], "permissions": ["governance.actor.role.revoke.execute"]},
    {"skillId": "governance.actor.status.set", "mode": "write", "auditClass": "write-critical", "humanConfirmationRequired": true, "roles": [], "permissions": ["governance.actor.status.set.execute"]},
    {"skillId": "governance.policy_candidate.review", "mode": "write", "auditClass": "write-critical", "humanConfirmationRequired": true, "roles": [], "permissions": ["governance.policy_candidate.review.execute"]},
    {"skillId": "objection.case.accept", "mode": "write", "auditClass": "write-normal", "humanConfirmationRequired": true, "roles": [], "permissions": ["objection.case.accept.execute"]},
    {"skillId": "objection.case.close", "mode": "write", "auditClass": "write-normal", "humanConfirmationRequired": true, "roles": [], "permissions": ["objection.case.close.execute"]},
    {"skillId": "objection.case.create", "mode": "write", "auditClass": "write-normal", "humanConfirmationRequired": true, "roles": [], "permissions": ["objection.case.create.execute"]},
    {"skillId": "objection.case.escalate", "mode": "write", "auditClass": "write-normal", "humanConfirmationRequired": true, "roles": [], "permissions": ["objection.case.escalate.execute"]},
    {"skillId": "objection.case.evaluate", "mode": "write", "auditClass": "write-normal", "humanConfirmationRequired": true, "roles": [], "permissions": ["objection.case.evaluate.execute"]},
    {"skillId": "objection.case.reply", "mode": "write", "auditClass": "write-normal", "humanConfirmationRequired": true, "roles": [], "permissions": ["objection.case.reply.execute"]},
    {"skillId": "objection.case.review", "mode": "write", "auditClass": "write-normal", "humanConfirmationRequired": true, "roles": [], "permissions": ["objection.case.review.execute"]},
    {"skillId": "objection.case.submit", "mode": "write", "auditClass": "write-normal", "humanConfirmationRequired": true, "roles": [], "permissions": ["objection.case.submit.execute"]},
  ] },
  { anchor: "B1.2", capabilities: [
    {"skillId": "package.list", "mode": "read", "auditClass": "read-default", "humanConfirmationRequired": false, "roles": [], "permissions": ["package.list.execute"]},
    {"skillId": "package.view", "mode": "read", "auditClass": "read-default", "humanConfirmationRequired": false, "roles": [], "permissions": ["package.view.execute"]},
    {"skillId": "tenant.policy.evaluate", "mode": "read", "auditClass": "read-trace", "humanConfirmationRequired": false, "roles": [], "permissions": ["tenant.policy.evaluate.execute"]},
    {"skillId": "approval_flow.nl_draft", "mode": "write", "auditClass": "read-normal", "humanConfirmationRequired": false, "roles": [], "permissions": ["approval_flow.nl_draft.execute"]},
    {"skillId": "approval_flow.schema.commit", "mode": "write", "auditClass": "write-critical", "humanConfirmationRequired": true, "roles": [], "permissions": ["approval_flow.schema.commit.execute"]},
    {"skillId": "approval_flow.schema.promote_to_preview", "mode": "write", "auditClass": "write-normal", "humanConfirmationRequired": true, "roles": [], "permissions": ["approval_flow.schema.promote_to_preview.execute"]},
    {"skillId": "approval_flow.schema.revert_to_draft", "mode": "write", "auditClass": "write-normal", "humanConfirmationRequired": true, "roles": [], "permissions": ["approval_flow.schema.revert_to_draft.execute"]},
    {"skillId": "capability.version.review", "mode": "write", "auditClass": "write-critical", "humanConfirmationRequired": true, "roles": [], "permissions": ["capability.version.review.execute"]},
    {"skillId": "form_schema.commit", "mode": "write", "auditClass": "write-critical", "humanConfirmationRequired": true, "roles": [], "permissions": ["form_schema.commit.execute"]},
    {"skillId": "form_schema.nl_draft", "mode": "write", "auditClass": "read-normal", "humanConfirmationRequired": false, "roles": [], "permissions": ["form_schema.nl_draft.execute"]},
    {"skillId": "form_schema.promote_to_preview", "mode": "write", "auditClass": "write-normal", "humanConfirmationRequired": true, "roles": [], "permissions": ["form_schema.promote_to_preview.execute"]},
    {"skillId": "form_schema.revert_to_draft", "mode": "write", "auditClass": "write-normal", "humanConfirmationRequired": true, "roles": [], "permissions": ["form_schema.revert_to_draft.execute"]},
    {"skillId": "package.review_decide", "mode": "write", "auditClass": "write-critical", "humanConfirmationRequired": true, "roles": [], "permissions": ["package.review_decide.execute"]},
    {"skillId": "package.rollback", "mode": "write", "auditClass": "write-critical", "humanConfirmationRequired": true, "roles": [], "permissions": ["package.rollback.execute"]},
    {"skillId": "package.trust_level.update", "mode": "write", "auditClass": "write-critical", "humanConfirmationRequired": true, "roles": [], "permissions": ["package.trust_level.update.execute"]},
    {"skillId": "recommendation.rule.commit", "mode": "write", "auditClass": "write-critical", "humanConfirmationRequired": true, "roles": [], "permissions": ["recommendation.rule.commit.execute"]},
    {"skillId": "tenant.capability.disable", "mode": "write", "auditClass": "write-critical", "humanConfirmationRequired": true, "roles": [], "permissions": ["tenant.capability.disable.execute"]},
    {"skillId": "tenant.capability.enable", "mode": "write", "auditClass": "write-critical", "humanConfirmationRequired": true, "roles": [], "permissions": ["tenant.capability.enable.execute"]},
  ] },
];

export const UNMAPPED_WEBUI_SKILLS: string[] = ["assistant.investigation_summary", "datasource.connectivity.test", "datasource.endpoint.delete", "datasource.endpoint.list", "datasource.endpoint.upsert", "datasource.table.columns", "datasource.table.list", "demand.list", "demand.phase.advance", "demand.register", "platform.docs.read", "platform.docs.search", "reference.dict.options", "reference.organ.options", "reference.region.options", "search.intent.parse"];
