#!/usr/bin/env python3
"""capture_feature_status.py — 每-feature 测量捕获（MEASUREMENT 原料）.

把"测试真的跑过且绿"固化成可机读、带 git_sha 溯源的产物，供状态函数 green() 读。
**禁止手写 result——本脚本现场跑测试，退出码即事实**（同 capture_acceptance_evidence）。

做法（test-runner 无关）：收集所有 `.feature` 的 `# Pytest:` 里的唯一测试 ref——
  - `tests/**.py` pytest 模块：逐个 `pytest <模块> -q`，退出码即 pass/fail；
  - `tests/**.spec.ts` Playwright e2e：仅 `--with-e2e` 时逐个 `playwright test <spec>` 实跑
    （需 :8800 全栈在跑，见 scripts/start-local.sh）；不开则记 `e2e-not-run`。
再把结果回填到每个 feature（feature 绿 = 其全部 ref 都 pass）。任一 ref 未跑/未绿 → feature 非绿
（fail-closed：e2e 未实跑绝不算绿，杜绝伪造）。

**R-001 vacuous-skip 守卫**：退出码 0 ≠ 真跑过。pytest 全 skip / Playwright 全 skip 退出码也是 0，
旧实现只看退出码 → 被记 pass（实证：national_channel.spec.ts 4 用例因起栈未开 flag 全 skip 冒绿，
撑起 national-direct/national-ext-elements 两个 Done）。现在解析 runner 汇总，**passed==0 一律记
vacuous-skip**（按非绿 fail-closed）。故起栈跑 e2e 时须把会 skip 的前置 flag 打开，否则相关
feature 自动掉绿——尤其 `ZW_BRAIN_NATIONAL_CHANNEL_ENABLED=1`（让 national_channel.spec.ts 真跑，
flag-on 未配置即 ON_UNPROVISIONED 真实态，不需 provisioning 凭据；见
docs/decisions/national-platform-access-D50.md env 契约）。

为什么纳入 e2e：webui 类 feature 只有 .spec.ts、pytest 轴看不到，旧版把 .ts 记 `web-skip`
导致它们永远非绿、即便签字也卡死 Ready。现在 green() 信任产物里的聚合 result，与 runner 无关。

每 feature 还写 `fingerprint`（`.feature`+引用测试文件内容哈希，D46.g 信任锚）。green() 据此判新鲜：
指纹失配即非绿、逼重采；**squash 免疫**（不再依赖 git_sha 是否 HEAD 祖先）。

产物：`.testing/status/measurement/<git_sha>.json`（**tracked + banner**，preflight 段 60 读，
`.data/` 是 gitignore 派生区不放这里）。`git_sha`/`captured_at` 仅作 provenance，不再当信任锚。

Usage:
    ./scripts/capture_feature_status.py [--captured-by "ci@<sha>"] [--with-e2e]
"""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from check_trace_triangle import _parse_feature_header  # noqa: E402
from feature_status_lib import (  # noqa: E402
    MEASUREMENT_DIR,
    REPO,
    all_features,
    feature_fingerprint,
    feature_rel,
    test_refs,
)

BANNER = "AUTO-GENERATED by scripts/capture_feature_status.py — DO NOT EDIT BY HAND (机器实跑 pytest/e2e 产出)"


def _git_sha() -> str:
    try:
        return subprocess.run(
            ["git", "rev-parse", "HEAD"], cwd=REPO, capture_output=True, text=True, check=True
        ).stdout.strip()
    except Exception:
        return "unknown"


def _py() -> str:
    # ZW_BRAIN_CAPTURE_PYTHON 覆盖：py312 门控的 feature（vendored AR wheel 是 py312-pyc-only，
    # 见 vendor/agent-runtime/README.md）只在 py312 环境真跑；此时把整套采量指向
    # .venv-py312/bin/python（与 start-local.sh 的 ZW_BRAIN_PYTHON_BIN 同源）。
    override = os.environ.get("ZW_BRAIN_CAPTURE_PYTHON", "").strip()
    if override:
        return override
    p = REPO / ".venv" / "bin" / "python"
    return str(p) if p.exists() else sys.executable


# 单测试上限：防单个集成测试因外部依赖卡住。
# 把整次 capture 吊死成僵尸。超时 → fail-closed（标 fail，绝不冒绿），capture 必然终止。
_MODULE_TIMEOUT_S = 900
_E2E_TIMEOUT_S = 600

# R-001（vacuous-skip 假绿修复）：退出码 0 ≠ 真跑过。pytest 全 skip / Playwright 全 skip 都
# 退 0；旧实现只看退出码 → 被记 pass，撑起 Done 的 e2e 轴（实证：national_channel.spec.ts
# 4 用例因起栈未开 flag 全 skip 被记 pass）。修法：解析 runner 汇总，**passed==0 一律记
# 非 pass**（标 vacuous-skip，green() 按非绿 fail-closed），不让"测试根本没跑"冒充绿。
_VACUOUS_SKIP = "vacuous-skip"

# pytest 末行汇总：如 "5 passed, 2 skipped in 1.2s" / "3 skipped in 0.4s" /
# "1 failed, 2 passed in ..." / "no tests ran in 0.01s"。逐 outcome 抓计数。
# （注：不能用 `-q`——叠 addopts 的 `-q` 双静默会吞掉此汇总行，见 _run_module 旁注。）
_PYTEST_COUNT_RE = re.compile(r"(\d+)\s+(passed|failed|error|errors|skipped|xfailed|xpassed|deselected)")
# Playwright list reporter 末段汇总：如 "5 passed (3.2s)" / "4 skipped" /
# "2 failed" / "1 flaky"。逐 outcome 抓计数。
_PW_COUNT_RE = re.compile(r"(\d+)\s+(passed|failed|skipped|flaky|interrupted|did not run)")


def _pytest_counts(out: str) -> dict[str, int]:
    counts: dict[str, int] = {}
    for n, kind in _PYTEST_COUNT_RE.findall(out):
        counts[kind] = counts.get(kind, 0) + int(n)
    return counts


def _classify_pytest(returncode: int, out: str) -> tuple[str, str]:
    """退出码 + 汇总联合判定。passed==0 → vacuous-skip（fail-closed，绝不冒绿）。"""
    counts = _pytest_counts(out)
    summary = ", ".join(f"{v} {k}" for k, v in counts.items()) or f"exit {returncode}"
    if returncode != 0:
        return "fail", summary
    passed = counts.get("passed", 0) + counts.get("xpassed", 0)
    if passed == 0:
        # 退 0 但零通过（全 skip / no tests ran / 仅 deselected）→ 测试未真跑，不算绿。
        return _VACUOUS_SKIP, f"退 0 但 passed==0（{summary}）— 未真跑，fail-closed"
    return "pass", summary


def _classify_e2e(returncode: int, out: str) -> tuple[str, str]:
    """Playwright list reporter 同理：passed==0 → vacuous-skip。"""
    counts: dict[str, int] = {}
    for n, kind in _PW_COUNT_RE.findall(out):
        counts[kind] = counts.get(kind, 0) + int(n)
    summary = ", ".join(f"{v} {k}" for k, v in counts.items()) or f"exit {returncode}"
    if returncode != 0:
        return "fail", summary
    if counts.get("passed", 0) == 0:
        return _VACUOUS_SKIP, f"退 0 但 passed==0（{summary}）— e2e 未真跑，fail-closed"
    return "pass", summary


def _run_module(module: str) -> tuple[str, str]:
    """跑单个 pytest 模块；返回 (pass|fail|vacuous-skip, detail)。

    退出码 + 汇总联合判定（R-001）：退 0 但 passed==0（全 skip / no tests ran）→ vacuous-skip，
    green() 按非绿处理，绝不让"没真跑"冒充绿。超时→fail-closed。
    """
    first = _run_module_once(module)
    if first[0] == "pass":
        return first
    second = _run_module_once(module)
    if second[0] == "pass":
        return "pass", f"{second[1]}（retry-after: {first[0]} {first[1]}）"
    return second[0], f"{second[1]}（retry-after: {first[0]} {first[1]}）"


def _run_module_once(module: str) -> tuple[str, str]:
    try:
        # 关键（R-001）：**不传 `-q`**。pyproject addopts 已含 `-q`，再叠一个 `-q`（双静默）
        # 会让 pytest 在"快速全绿"短跑时**吞掉末行汇总**（输出只剩进度点 `....[100%]`、无
        # "N passed"），导致 _classify_pytest 抓不到 passed 计数 → 误判 vacuous-skip。去掉显式
        # `-q` 后汇总恒打印（"12 passed in 0.8s"）。`--tb=no` 压掉 traceback 保持输出紧凑，
        # 但保留汇总行（失败计数仍在）。`-rN` 不加（无额外摘要需求）。
        p = subprocess.run(
            [_py(), "-m", "pytest", module, "--tb=no", "-p", "no:cacheprovider"],
            cwd=REPO, capture_output=True, text=True, timeout=_MODULE_TIMEOUT_S,
        )
    except subprocess.TimeoutExpired:
        return "fail", f"timeout >{_MODULE_TIMEOUT_S}s（疑挂死，fail-closed）"
    return _classify_pytest(p.returncode, p.stdout + p.stderr)


def _run_e2e_spec(spec: str) -> tuple[str, str]:
    """跑单个 Playwright e2e spec（需 :8800 全栈在跑）；返回 (pass|fail|vacuous-skip, detail)。

    退出码 + 汇总联合判定（R-001）：退 0 但 passed==0（全 skip，如 flag 未开）→ vacuous-skip。
    超时→fail-closed。
    """
    try:
        p = subprocess.run(
            ["npx", "playwright", "test", spec, "--reporter=list"],
            cwd=REPO, capture_output=True, text=True, timeout=_E2E_TIMEOUT_S,
        )
    except subprocess.TimeoutExpired:
        return "fail", f"timeout >{_E2E_TIMEOUT_S}s（疑挂死，fail-closed）"
    return _classify_e2e(p.returncode, p.stdout + p.stderr)


def main() -> int:
    ap = argparse.ArgumentParser(description="每-feature 测量捕获（MEASUREMENT）")
    ap.add_argument("--captured-by", default="", help="采集人/CI 标识")
    ap.add_argument("--with-e2e", action="store_true",
                    help="实跑 .spec.ts Playwright e2e（需 :8800 全栈，见 start-local.sh）；不开则记 e2e-not-run")
    ap.add_argument("--e2e-allowlist", default="",
                    help="逗号分隔的 e2e spec 基名（如 webui_smoke.spec.ts）；仅实跑清单内 spec，"
                         "清单外记 e2e-not-run（CI seed-light：committed seed_snapshot.json 能干净跑的子集，"
                         "dump-依赖 spec 留本地，绝不假绿）。空=不限（实跑全部 e2e）。")
    ap.add_argument("--e2e-only", action="store_true",
                    help="只跑 e2e 轴、跳过 pytest 模块（CI 的 test job 已覆盖 pytest，避免重复 ~10min）；"
                         "feature 结果仅按 e2e ref 评，产物为 CI 验证态（不入库提交）。")
    args = ap.parse_args()
    e2e_allow = {s.strip() for s in args.e2e_allowlist.split(",") if s.strip()}

    # feature → 其测试 refs（.py + .spec.ts）+ 内容指纹（信任锚，D46.g）
    feat_refs: dict[str, list[str]] = {}
    feat_fp: dict[str, str] = {}
    for path in all_features():
        _, pytest_val, _ = _parse_feature_header(path)
        rel = feature_rel(path)
        feat_refs[rel] = test_refs(pytest_val)
        feat_fp[rel] = feature_fingerprint(path)

    # 唯一 .py 模块实跑（pytest）；--e2e-only 跳过（CI test job 已覆盖）
    py_modules = sorted({r for refs in feat_refs.values() for r in refs if r.endswith(".py")})
    module_result: dict[str, tuple[str, str]] = {}
    if not args.e2e_only:
        for m in py_modules:
            module_result[m] = _run_module(m)
            print(f"  [{module_result[m][0]}] {m}: {module_result[m][1]}")

    # 唯一 .spec.ts e2e：仅 --with-e2e 实跑，否则记 e2e-not-run（fail-closed）。
    # --e2e-allowlist 非空时，清单外 spec 记 e2e-not-run（CI seed-light 范围，不假绿）。
    ts_specs = sorted({r for refs in feat_refs.values() for r in refs if r.endswith(".spec.ts")})
    for s in ts_specs:
        spec_name = s.rsplit("/", 1)[-1]
        if not args.with_e2e:
            module_result[s] = ("e2e-not-run", "未开 --with-e2e（e2e 需 :8800 全栈实跑）")
        elif e2e_allow and spec_name not in e2e_allow:
            module_result[s] = ("e2e-not-run", "不在 CI seed-light allowlist（dump-依赖，留本地实跑）")
        else:
            module_result[s] = _run_e2e_spec(s)
        print(f"  [{module_result[s][0]}] {s}: {module_result[s][1]}")

    # 回填每 feature：绿 = 全部 ref pass；任一未跑/未绿 → 非绿。
    # --e2e-only：只按 e2e ref 评（pytest 轴由 test job 覆盖），pytest-only feature 记 e2e-axis-skip。
    features: dict[str, dict] = {}
    for rel, refs in feat_refs.items():
        eval_refs = [r for r in refs if r.endswith(".spec.ts")] if args.e2e_only else refs
        if args.e2e_only and not eval_refs:
            result, detail = "e2e-axis-skip", "e2e-only：本 feature 无 e2e ref（pytest 轴由 test job 评）"
        elif not eval_refs:
            result, detail = "no-tests", "无测试 ref（pending）"
        else:
            refs = eval_refs
            statuses = [module_result.get(r, ("fail", ""))[0] for r in refs]
            if all(s == "pass" for s in statuses):
                result, detail = "pass", "全部测试 ref 绿"
            elif any(s == "fail" for s in statuses):
                result = "fail"
                detail = f"未绿 ref {[r for r, s in zip(refs, statuses, strict=True) if s == 'fail']}"
            elif any(s == _VACUOUS_SKIP for s in statuses):
                # R-001：任一 ref 全 skip（退 0 但 passed==0）→ 整 feature 非绿，fail-closed。
                # 与 fail 同级（不冒绿），但单列状态名以便 PR/审计区分"红"与"没真跑"。
                result = _VACUOUS_SKIP
                detail = f"测试未真跑（全 skip）{[r for r, s in zip(refs, statuses, strict=True) if s == _VACUOUS_SKIP]}"
            else:  # 无 fail / vacuous，但有 e2e-not-run
                result = "e2e-not-run"
                detail = f"e2e 未实跑 {[r for r, s in zip(refs, statuses, strict=True) if s == 'e2e-not-run']}"
        features[rel] = {"test_refs": refs, "result": result, "detail": detail,
                         "fingerprint": feat_fp[rel]}

    sha = _git_sha()
    artifact = {
        "_generated_by": BANNER,
        "git_sha": sha,
        "captured_at": datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "captured_by": args.captured_by,
        "with_e2e": args.with_e2e,
        "e2e_only": args.e2e_only,
        "e2e_allowlist": sorted(e2e_allow),
        "module_results": {m: {"result": r, "detail": d} for m, (r, d) in module_result.items()},
        "features": features,
    }
    MEASUREMENT_DIR.mkdir(parents=True, exist_ok=True)
    # 范围受限运行（CI seed-light / e2e-only）写 ci-scoped/ 子目录，绝不覆盖、也不被
    # check_feature_measurement 的 MEASUREMENT_DIR.glob("*.json")（非递归）当成权威测量产物
    # ——canonical {sha}.json（作者本地全量采集 + 提交入库的那份）才是单一事实源。
    scoped = args.e2e_only or bool(e2e_allow)
    if scoped:
        (MEASUREMENT_DIR / "ci-scoped").mkdir(parents=True, exist_ok=True)
        out = MEASUREMENT_DIR / "ci-scoped" / f"{sha}.json"
    else:
        out = MEASUREMENT_DIR / f"{sha}.json"
    out.write_text(json.dumps(artifact, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    mod_fail = sum(1 for r, _ in module_result.values() if r == "fail")
    mod_vacuous = sum(1 for r, _ in module_result.values() if r == _VACUOUS_SKIP)
    not_run = sum(1 for r, _ in module_result.values() if r == "e2e-not-run")
    feat_pass = sum(1 for f in features.values() if f["result"] == "pass")
    print(f"[capture-feature-status] wrote {out.relative_to(REPO)} — "
          f"{len(py_modules)} pytest + {len(ts_specs)} e2e"
          f"（{mod_fail} fail, {mod_vacuous} vacuous-skip, {not_run} e2e-not-run），"
          f"{feat_pass}/{len(features)} feature 绿")
    # R-001：vacuous-skip 与 fail 同样属"未真跑/未真绿"，退非零让 CI/调用方知晓。
    return 1 if (mod_fail or mod_vacuous) else 0


if __name__ == "__main__":
    sys.exit(main())
