#!/usr/bin/env python3
"""capture_feature_status.py — 每-feature 测量捕获（MEASUREMENT 原料）.

把"测试真的跑过且绿"固化成可机读、带 git_sha 溯源的产物，供状态函数 green() 读。
**禁止手写 result——本脚本现场跑测试，退出码即事实**（同 capture_acceptance_evidence）。

做法（test-runner 无关）：收集所有 `.feature` 的 `# Pytest:` 里的唯一测试 ref——
  - `tests/**.py` pytest 模块：逐个 `pytest <模块> -q`，退出码即 pass/fail；
  - `tests/**.spec.ts` Playwright e2e：仅 `--with-e2e` 时逐个 `playwright test <spec>` 实跑
    （需 :8800 全栈在跑，见 scripts/start-local.sh）；不开则记 `e2e-not-run`。
再把结果回填到每个 feature（feature 绿 = 其全部 ref 都 pass）。任一 ref 未跑/未绿 → feature 非绿
（fail-closed：e2e 未实跑绝不算绿，杜绝伪造）。

为什么纳入 e2e：webui 类 feature 只有 .spec.ts、pytest 轴看不到，旧版把 .ts 记 `web-skip`
导致它们永远非绿、即便签字也卡死 Ready。现在 green() 信任产物里的聚合 result，与 runner 无关。

产物：`.testing/status/measurement/<git_sha>.json`（**tracked + banner**，preflight 段 60 读，
`.data/` 是 gitignore 派生区不放这里）。preflight 不跑测试，只读本产物且 git_sha 须 HEAD 祖先。

Usage:
    ./scripts/capture_feature_status.py [--captured-by "ci@<sha>"] [--with-e2e]
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from check_trace_triangle import _parse_feature_header  # noqa: E402
from feature_status_lib import (  # noqa: E402
    MEASUREMENT_DIR,
    REPO,
    all_features,
    feature_rel,
    test_refs,
)

BANNER = "AUTO-GENERATED by scripts/capture_feature_status.py — DO NOT EDIT BY HAND (机器实跑 pytest/e2e 产出)"


def _git_sha() -> str:
    try:
        return subprocess.run(
            ["git", "rev-parse", "HEAD"], cwd=REPO, capture_output=True, text=True, check=True
        ).stdout.strip()
    except Exception:
        return "unknown"


def _py() -> str:
    p = REPO / ".venv" / "bin" / "python"
    return str(p) if p.exists() else sys.executable


def _run_module(module: str) -> tuple[str, str]:
    """跑单个 pytest 模块；返回 (pass|fail, detail)。退出码即事实。"""
    p = subprocess.run(
        [_py(), "-m", "pytest", module, "-q", "-p", "no:cacheprovider"],
        cwd=REPO, capture_output=True, text=True,
    )
    tail = (p.stdout + p.stderr).strip().splitlines()
    return ("pass" if p.returncode == 0 else "fail"), (tail[-1] if tail else f"exit {p.returncode}")


def _run_e2e_spec(spec: str) -> tuple[str, str]:
    """跑单个 Playwright e2e spec（需 :8800 全栈在跑）；返回 (pass|fail, detail)。退出码即事实。"""
    p = subprocess.run(
        ["npx", "playwright", "test", spec, "--reporter=list"],
        cwd=REPO, capture_output=True, text=True,
    )
    tail = (p.stdout + p.stderr).strip().splitlines()
    return ("pass" if p.returncode == 0 else "fail"), (tail[-1] if tail else f"exit {p.returncode}")


def main() -> int:
    ap = argparse.ArgumentParser(description="每-feature 测量捕获（MEASUREMENT）")
    ap.add_argument("--captured-by", default="", help="采集人/CI 标识")
    ap.add_argument("--with-e2e", action="store_true",
                    help="实跑 .spec.ts Playwright e2e（需 :8800 全栈，见 start-local.sh）；不开则记 e2e-not-run")
    args = ap.parse_args()

    # feature → 其测试 refs（.py + .spec.ts）
    feat_refs: dict[str, list[str]] = {}
    for path in all_features():
        _, pytest_val, _ = _parse_feature_header(path)
        feat_refs[feature_rel(path)] = test_refs(pytest_val)

    # 唯一 .py 模块实跑（pytest）
    py_modules = sorted({r for refs in feat_refs.values() for r in refs if r.endswith(".py")})
    module_result: dict[str, tuple[str, str]] = {}
    for m in py_modules:
        module_result[m] = _run_module(m)
        print(f"  [{module_result[m][0]}] {m}: {module_result[m][1]}")

    # 唯一 .spec.ts e2e：仅 --with-e2e 实跑，否则记 e2e-not-run（fail-closed）
    ts_specs = sorted({r for refs in feat_refs.values() for r in refs if r.endswith(".spec.ts")})
    for s in ts_specs:
        if args.with_e2e:
            module_result[s] = _run_e2e_spec(s)
        else:
            module_result[s] = ("e2e-not-run", "未开 --with-e2e（e2e 需 :8800 全栈实跑）")
        print(f"  [{module_result[s][0]}] {s}: {module_result[s][1]}")

    # 回填每 feature：绿 = 全部 ref pass；任一未跑/未绿 → 非绿
    features: dict[str, dict] = {}
    for rel, refs in feat_refs.items():
        if not refs:
            result, detail = "no-tests", "无测试 ref（pending）"
        else:
            statuses = [module_result.get(r, ("fail", ""))[0] for r in refs]
            if all(s == "pass" for s in statuses):
                result, detail = "pass", "全部测试 ref 绿"
            elif any(s == "fail" for s in statuses):
                result = "fail"
                detail = f"未绿 ref {[r for r, s in zip(refs, statuses, strict=True) if s == 'fail']}"
            else:  # 无 fail，但有 e2e-not-run
                result = "e2e-not-run"
                detail = f"e2e 未实跑 {[r for r, s in zip(refs, statuses, strict=True) if s == 'e2e-not-run']}"
        features[rel] = {"test_refs": refs, "result": result, "detail": detail}

    sha = _git_sha()
    artifact = {
        "_generated_by": BANNER,
        "git_sha": sha,
        "captured_at": datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "captured_by": args.captured_by,
        "with_e2e": args.with_e2e,
        "module_results": {m: {"result": r, "detail": d} for m, (r, d) in module_result.items()},
        "features": features,
    }
    MEASUREMENT_DIR.mkdir(parents=True, exist_ok=True)
    out = MEASUREMENT_DIR / f"{sha}.json"
    out.write_text(json.dumps(artifact, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    mod_fail = sum(1 for r, _ in module_result.values() if r == "fail")
    not_run = sum(1 for r, _ in module_result.values() if r == "e2e-not-run")
    feat_pass = sum(1 for f in features.values() if f["result"] == "pass")
    print(f"[capture-feature-status] wrote {out.relative_to(REPO)} — "
          f"{len(py_modules)} pytest + {len(ts_specs)} e2e（{mod_fail} fail, {not_run} e2e-not-run），"
          f"{feat_pass}/{len(features)} feature 绿")
    return 1 if mod_fail else 0


if __name__ == "__main__":
    sys.exit(main())
