#!/usr/bin/env python3
"""capture_feature_status.py — 每-feature 测量捕获（MEASUREMENT 原料）.

把"测试真的跑过且绿"固化成可机读、带 git_sha 溯源的产物，供状态函数 green() 读。
**禁止手写 result——本脚本现场跑测试，退出码即事实**（同 capture_acceptance_evidence）。

做法（test-runner 无关）：收集所有 `.feature` 的 `# Pytest:` 里的唯一测试 ref——
  - `tests/**.py` pytest 模块：逐个 `pytest <模块> -q`，退出码即 pass/fail；
  - `tests/**.spec.ts` Playwright e2e：仅 `--with-e2e` 时逐个 `playwright test <spec>` 实跑
    （需 :8800 全栈在跑，见 scripts/start-local.sh）；不开则记 `e2e-not-run`。
再把结果回填到每个 feature（feature 绿 = 其全部 ref 都 pass）。任一 ref 未跑/未绿 → feature 非绿
（fail-closed：e2e 未实跑绝不算绿，杜绝伪造）。

为什么纳入 e2e：webui 类 feature 只有 .spec.ts、pytest 轴看不到，旧版把 .ts 记 `web-skip`
导致它们永远非绿、即便签字也卡死 Ready。现在 green() 信任产物里的聚合 result，与 runner 无关。

每 feature 还写 `fingerprint`（`.feature`+引用测试文件内容哈希，D46.g 信任锚）。green() 据此判新鲜：
指纹失配即非绿、逼重采；**squash 免疫**（不再依赖 git_sha 是否 HEAD 祖先）。

产物：`.testing/status/measurement/<git_sha>.json`（**tracked + banner**，preflight 段 60 读，
`.data/` 是 gitignore 派生区不放这里）。`git_sha`/`captured_at` 仅作 provenance，不再当信任锚。

Usage:
    ./scripts/capture_feature_status.py [--captured-by "ci@<sha>"] [--with-e2e]
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from check_trace_triangle import _parse_feature_header  # noqa: E402
from feature_status_lib import (  # noqa: E402
    MEASUREMENT_DIR,
    REPO,
    all_features,
    feature_fingerprint,
    feature_rel,
    test_refs,
)

BANNER = "AUTO-GENERATED by scripts/capture_feature_status.py — DO NOT EDIT BY HAND (机器实跑 pytest/e2e 产出)"


def _git_sha() -> str:
    try:
        return subprocess.run(
            ["git", "rev-parse", "HEAD"], cwd=REPO, capture_output=True, text=True, check=True
        ).stdout.strip()
    except Exception:
        return "unknown"


def _py() -> str:
    # ZW_BRAIN_CAPTURE_PYTHON 覆盖：SDK 门控的 feature（如 infra-agentruntime-embedded 的
    # tests/test_agentruntime_embedded.py importorskip agent_runtime）只在 py312 + vendored
    # SDK 环境真跑（vendor wheel 是 py312-pyc-only，见 vendor/agent-runtime/README.md）；
    # 此时把整套采量指向 .venv-py312/bin/python（与 start-local.sh 的 ZW_BRAIN_PYTHON_BIN 同源）。
    override = os.environ.get("ZW_BRAIN_CAPTURE_PYTHON", "").strip()
    if override:
        return override
    p = REPO / ".venv" / "bin" / "python"
    return str(p) if p.exists() else sys.executable


# 单测试上限：防一个挂死测试（如真推理网关缺失时 test_inference_client 的网络 connect 吊死）
# 把整次 capture 吊死成僵尸。超时 → fail-closed（标 fail，绝不冒绿），capture 必然终止。
_MODULE_TIMEOUT_S = 900
_E2E_TIMEOUT_S = 600


def _run_module(module: str) -> tuple[str, str]:
    """跑单个 pytest 模块；返回 (pass|fail, detail)。退出码即事实；超时→fail-closed。"""
    try:
        p = subprocess.run(
            [_py(), "-m", "pytest", module, "-q", "-p", "no:cacheprovider"],
            cwd=REPO, capture_output=True, text=True, timeout=_MODULE_TIMEOUT_S,
        )
    except subprocess.TimeoutExpired:
        return "fail", f"timeout >{_MODULE_TIMEOUT_S}s（疑挂死，fail-closed）"
    tail = (p.stdout + p.stderr).strip().splitlines()
    return ("pass" if p.returncode == 0 else "fail"), (tail[-1] if tail else f"exit {p.returncode}")


def _run_e2e_spec(spec: str) -> tuple[str, str]:
    """跑单个 Playwright e2e spec（需 :8800 全栈在跑）；返回 (pass|fail, detail)。超时→fail-closed。"""
    try:
        p = subprocess.run(
            ["npx", "playwright", "test", spec, "--reporter=list"],
            cwd=REPO, capture_output=True, text=True, timeout=_E2E_TIMEOUT_S,
        )
    except subprocess.TimeoutExpired:
        return "fail", f"timeout >{_E2E_TIMEOUT_S}s（疑挂死，fail-closed）"
    tail = (p.stdout + p.stderr).strip().splitlines()
    return ("pass" if p.returncode == 0 else "fail"), (tail[-1] if tail else f"exit {p.returncode}")


def main() -> int:
    ap = argparse.ArgumentParser(description="每-feature 测量捕获（MEASUREMENT）")
    ap.add_argument("--captured-by", default="", help="采集人/CI 标识")
    ap.add_argument("--with-e2e", action="store_true",
                    help="实跑 .spec.ts Playwright e2e（需 :8800 全栈，见 start-local.sh）；不开则记 e2e-not-run")
    ap.add_argument("--e2e-allowlist", default="",
                    help="逗号分隔的 e2e spec 基名（如 webui_smoke.spec.ts）；仅实跑清单内 spec，"
                         "清单外记 e2e-not-run（CI seed-light：committed seed_snapshot.json 能干净跑的子集，"
                         "dump-依赖 spec 留本地，绝不假绿）。空=不限（实跑全部 e2e）。")
    ap.add_argument("--e2e-only", action="store_true",
                    help="只跑 e2e 轴、跳过 pytest 模块（CI 的 test job 已覆盖 pytest，避免重复 ~10min）；"
                         "feature 结果仅按 e2e ref 评，产物为 CI 验证态（不入库提交）。")
    args = ap.parse_args()
    e2e_allow = {s.strip() for s in args.e2e_allowlist.split(",") if s.strip()}

    # feature → 其测试 refs（.py + .spec.ts）+ 内容指纹（信任锚，D46.g）
    feat_refs: dict[str, list[str]] = {}
    feat_fp: dict[str, str] = {}
    for path in all_features():
        _, pytest_val, _ = _parse_feature_header(path)
        rel = feature_rel(path)
        feat_refs[rel] = test_refs(pytest_val)
        feat_fp[rel] = feature_fingerprint(path)

    # 唯一 .py 模块实跑（pytest）；--e2e-only 跳过（CI test job 已覆盖）
    py_modules = sorted({r for refs in feat_refs.values() for r in refs if r.endswith(".py")})
    module_result: dict[str, tuple[str, str]] = {}
    if not args.e2e_only:
        for m in py_modules:
            module_result[m] = _run_module(m)
            print(f"  [{module_result[m][0]}] {m}: {module_result[m][1]}")

    # 唯一 .spec.ts e2e：仅 --with-e2e 实跑，否则记 e2e-not-run（fail-closed）。
    # --e2e-allowlist 非空时，清单外 spec 记 e2e-not-run（CI seed-light 范围，不假绿）。
    ts_specs = sorted({r for refs in feat_refs.values() for r in refs if r.endswith(".spec.ts")})
    for s in ts_specs:
        spec_name = s.rsplit("/", 1)[-1]
        if not args.with_e2e:
            module_result[s] = ("e2e-not-run", "未开 --with-e2e（e2e 需 :8800 全栈实跑）")
        elif e2e_allow and spec_name not in e2e_allow:
            module_result[s] = ("e2e-not-run", "不在 CI seed-light allowlist（dump-依赖，留本地实跑）")
        else:
            module_result[s] = _run_e2e_spec(s)
        print(f"  [{module_result[s][0]}] {s}: {module_result[s][1]}")

    # 回填每 feature：绿 = 全部 ref pass；任一未跑/未绿 → 非绿。
    # --e2e-only：只按 e2e ref 评（pytest 轴由 test job 覆盖），pytest-only feature 记 e2e-axis-skip。
    features: dict[str, dict] = {}
    for rel, refs in feat_refs.items():
        eval_refs = [r for r in refs if r.endswith(".spec.ts")] if args.e2e_only else refs
        if args.e2e_only and not eval_refs:
            result, detail = "e2e-axis-skip", "e2e-only：本 feature 无 e2e ref（pytest 轴由 test job 评）"
        elif not eval_refs:
            result, detail = "no-tests", "无测试 ref（pending）"
        else:
            refs = eval_refs
            statuses = [module_result.get(r, ("fail", ""))[0] for r in refs]
            if all(s == "pass" for s in statuses):
                result, detail = "pass", "全部测试 ref 绿"
            elif any(s == "fail" for s in statuses):
                result = "fail"
                detail = f"未绿 ref {[r for r, s in zip(refs, statuses, strict=True) if s == 'fail']}"
            else:  # 无 fail，但有 e2e-not-run
                result = "e2e-not-run"
                detail = f"e2e 未实跑 {[r for r, s in zip(refs, statuses, strict=True) if s == 'e2e-not-run']}"
        features[rel] = {"test_refs": refs, "result": result, "detail": detail,
                         "fingerprint": feat_fp[rel]}

    sha = _git_sha()
    artifact = {
        "_generated_by": BANNER,
        "git_sha": sha,
        "captured_at": datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "captured_by": args.captured_by,
        "with_e2e": args.with_e2e,
        "e2e_only": args.e2e_only,
        "e2e_allowlist": sorted(e2e_allow),
        "module_results": {m: {"result": r, "detail": d} for m, (r, d) in module_result.items()},
        "features": features,
    }
    MEASUREMENT_DIR.mkdir(parents=True, exist_ok=True)
    # 范围受限运行（CI seed-light / e2e-only）写 ci-scoped/ 子目录，绝不覆盖、也不被
    # check_feature_measurement 的 MEASUREMENT_DIR.glob("*.json")（非递归）当成权威测量产物
    # ——canonical {sha}.json（作者本地全量采集 + 提交入库的那份）才是单一事实源。
    scoped = args.e2e_only or bool(e2e_allow)
    if scoped:
        (MEASUREMENT_DIR / "ci-scoped").mkdir(parents=True, exist_ok=True)
        out = MEASUREMENT_DIR / "ci-scoped" / f"{sha}.json"
    else:
        out = MEASUREMENT_DIR / f"{sha}.json"
    out.write_text(json.dumps(artifact, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    mod_fail = sum(1 for r, _ in module_result.values() if r == "fail")
    not_run = sum(1 for r, _ in module_result.values() if r == "e2e-not-run")
    feat_pass = sum(1 for f in features.values() if f["result"] == "pass")
    print(f"[capture-feature-status] wrote {out.relative_to(REPO)} — "
          f"{len(py_modules)} pytest + {len(ts_specs)} e2e（{mod_fail} fail, {not_run} e2e-not-run），"
          f"{feat_pass}/{len(features)} feature 绿")
    return 1 if mod_fail else 0


if __name__ == "__main__":
    sys.exit(main())
