#!/usr/bin/env python3
"""check_no_hand_maintained_projection.py — preflight 段 29

F4 落地：5 消费面投影器（WebUI 页面注册 / REST OpenAPI / CLI 命令树 / MCP 工具 / A2A 卡）
都派生自 zw_brain/skill_registration/registered/*.json 200 manifest。
本守卫保证：
  (1) export_agent_contract.py --check 通过（产物与代码 fresh），
  (2) 新增的 *.generated.* 投影文件头部含 AUTO-GENERATED banner（防止手改后通过 byte-diff
      校验误判，加一层文本层守卫）。

退出码：0 = 全部通过；1 = 有 drift 或 banner 缺失
"""
from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent


def _repo_python() -> list[str]:
    """Mirror scripts/preflight_common.sh::repo_python preference order:
       PYTHON_BIN env → .venv/bin/python → uv run python → current sys.executable.
    System python (e.g. /opt/homebrew/bin/python3) lacks zw_brain deps (jwt/sqlalchemy),
    so we need to find the actual venv where the project was installed.
    """
    env_python = os.environ.get("PYTHON_BIN")
    if env_python:
        return [env_python]
    venv_python = REPO / ".venv" / "bin" / "python"
    if venv_python.exists():
        return [str(venv_python)]
    if shutil.which("uv") and (REPO / "pyproject.toml").exists():
        return ["uv", "run", "python"]
    return [sys.executable]

# F4 5 投影目标路径表 ——（路径，banner 必须命中的子串）
# 前 3 个保持 spec-clean（MCP/OpenAPI/A2A card 要被外部工具消费，不能塞自定义字段）；
# 后 2 个是 F4 新增的内部投影，必须含 AUTO-GENERATED banner 防止手改。
PROJECTION_TARGETS: tuple[tuple[Path, str | None], ...] = (
    (REPO / "zw_brain" / "entry" / "rest" / "openapi.json", None),
    (REPO / "zw_brain" / "entry" / "a2a" / "agent_card.json", None),
    (REPO / "zw_brain" / "entry" / "a2a" / "tools" / "runtime_bindings.json", None),
    (REPO / "zw_brain" / "entry" / "mcp" / "tools", None),  # 目录，53+ 文件
    (REPO / "zw-brain-web" / "src" / "registry" / "pages.generated.ts",
     "AUTO-GENERATED by scripts/export_agent_contract.py"),
    (REPO / "zw_brain" / "entry" / "cli" / "commands.generated.json",
     "scripts/export_agent_contract.py — DO NOT EDIT BY HAND"),
)

REGEN_HINT = "  Run: python3 scripts/export_agent_contract.py"


def main() -> int:
    errors: list[str] = []

    # 1) 检查 banner —— 仅对 .generated.* 文件
    for path, banner in PROJECTION_TARGETS:
        if banner is None:
            continue
        if not path.exists():
            errors.append(f"missing projection: {path.relative_to(REPO)}")
            continue
        text = path.read_text(encoding="utf-8")
        if banner not in text:
            errors.append(
                f"projection {path.relative_to(REPO)} missing AUTO-GENERATED banner "
                f"(expected substring: {banner!r}) — file appears hand-edited"
            )

    # 2) 委托 export_agent_contract.py --check 做 byte-equality 漂移检测
    cmd = _repo_python() + [str(REPO / "scripts" / "export_agent_contract.py"), "--check"]
    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        for line in (proc.stdout + proc.stderr).splitlines():
            line = line.strip()
            if line:
                errors.append(line)
        errors.append("→ projection drift / 手改残留；上述差异条目代表 5 投影之一被人工修改")

    if errors:
        print("[no-hand-maintained-projection] FAIL", file=sys.stderr)
        for err in errors:
            print(f"  - {err}", file=sys.stderr)
        print(REGEN_HINT, file=sys.stderr)
        return 1

    print(
        "[no-hand-maintained-projection] OK: 5 消费面投影 + 53 MCP tool 描述符 + 1 doc 全部"
        " 与 200 manifest 同步；banner 完整"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
