#!/usr/bin/env python3
"""check_feature_measurement.py — preflight 段 60

MEASUREMENT 产物守卫：preflight 不跑 pytest（快/离线/可复现），只**读**
`.testing/status/measurement/<sha>.json`，校验 banner/schema 合法 + **内容指纹新鲜**。

信任锚 = 被测内容指纹（`.feature`+引用测试文件哈希，D46.g），**不是 git_sha**：
squash-merge 改写历史但不动文件内容 → 指纹不变 → 不再永久误报「孤儿/异线」；
测试或规格真变了却没重采 → 指纹失配 → **FAIL**，逼重采。**squash 免疫、不炸 main**。

  - 无任何产物 → skip（引入期允许；green() 全 False，fail-closed）
  - 产物缺 banner / features 结构非法 → FAIL
  - 最新产物里 result==pass 的 feature，其存的 fingerprint ≠ 当前文件指纹 → FAIL（陈旧，须重采）

Exit：0 = OK/skip；1 = 结构非法 / 测量陈旧
Usage: ./scripts/check_feature_measurement.py [--verbose]
接入：scripts/preflight.sh 段 60
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from feature_status_lib import (  # noqa: E402
    MEASUREMENT_DIR,
    REPO,
    all_features,
    feature_fingerprint,
    feature_rel,
    load_measurement,
)

BANNER_MARK = "AUTO-GENERATED by scripts/capture_feature_status.py"
RECAPTURE_HINT = "scripts/capture_feature_status.py --with-e2e（干净真库 + :8800 全栈）"


def main() -> int:
    ap = argparse.ArgumentParser(description="MEASUREMENT 产物守卫（段 60）")
    ap.add_argument("--verbose", action="store_true")
    ap.parse_args()

    if not MEASUREMENT_DIR.is_dir():
        print("[feature-measurement] skip: 无 .testing/status/measurement/（green() 全 False，fail-closed）")
        return 0
    files = sorted(MEASUREMENT_DIR.glob("*.json"))
    if not files:
        print("[feature-measurement] skip: 无测量产物")
        return 0

    # 1) 结构：每份产物 banner + features dict 合法
    fails: list[str] = []
    for fp in files:
        rel = fp.relative_to(REPO).as_posix()
        try:
            d = json.loads(fp.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError) as e:
            fails.append(f"{rel}: 解析失败 {e}")
            continue
        if BANNER_MARK not in str(d.get("_generated_by", "")):
            fails.append(f"{rel}: 缺 AUTO-GENERATED banner（疑手写产物）")
        if not isinstance(d.get("features"), dict):
            fails.append(f"{rel}: features 结构非法")
    if fails:
        print(f"[feature-measurement] FAIL: {len(fails)} 项结构非法：")
        for f in fails:
            print(f"  {f}")
        return 1

    # 2) 新鲜度：green() 实际读取的最新产物里，凡 result==pass 的 feature，
    #    其存的指纹必须 == 当前 `.feature`+测试文件指纹（squash 免疫的陈旧判定）。
    m = load_measurement()
    if m:
        rel_to_path = {feature_rel(p): p for p in all_features()}
        stale: list[str] = []
        for rel, rec in (m.get("features") or {}).items():
            if rec.get("result") != "pass":
                continue
            path = rel_to_path.get(rel)
            if path is None:
                continue  # feature 已删，忽略（不阻断）
            if rec.get("fingerprint") != feature_fingerprint(path):
                stale.append(rel.split("/")[-1])
        if stale:
            print(f"[feature-measurement] FAIL: {len(stale)} 个 feature 测量陈旧"
                  "（测试/规格已变或产物无指纹，旧 result 不可信）：")
            for s in stale:
                print(f"  {s}")
            print(f"  → 重采：{RECAPTURE_HINT}")
            return 1

    n_pass = sum(1 for r in (m or {}).get("features", {}).values() if r.get("result") == "pass")
    print(f"[feature-measurement] OK: {len(files)} 份产物结构合法，{n_pass} 个绿 feature 指纹新鲜")
    return 0


if __name__ == "__main__":
    sys.exit(main())
