#!/usr/bin/env python3
"""check_feature_measurement.py — preflight 段 60

MEASUREMENT 产物守卫：preflight 不跑 pytest（快/离线/可复现），只**读**
`.testing/status/measurement/<sha>.json` 并要求其 git_sha 为 HEAD 祖先才信任
（同段 55 D37 证据陈旧校验）。banner 完整 + schema 合法。

  - 无任何产物 → skip（Phase 引入期允许；状态函数 green() 自动全 False，fail-closed）
  - 有产物但无一个 git_sha 是 HEAD 祖先 → WARN（陈旧/异线，建议重跑 capture）
  - 产物缺 banner / features 结构 → FAIL

Exit：0 = OK/skip/WARN；1 = 结构非法
Usage: ./scripts/check_feature_measurement.py [--verbose]
接入：scripts/preflight.sh 段 60
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from feature_status_lib import MEASUREMENT_DIR, REPO  # noqa: E402

BANNER_MARK = "AUTO-GENERATED by scripts/capture_feature_status.py"


def _is_ancestor(sha: str) -> bool:
    if not sha or sha == "unknown":
        return False
    return subprocess.run(
        ["git", "merge-base", "--is-ancestor", sha, "HEAD"], cwd=REPO, capture_output=True
    ).returncode == 0


def main() -> int:
    ap = argparse.ArgumentParser(description="MEASUREMENT 产物守卫（段 60）")
    ap.add_argument("--verbose", action="store_true")
    ap.parse_args()

    if not MEASUREMENT_DIR.is_dir():
        print("[feature-measurement] skip: 无 .testing/status/measurement/（green() 全 False，fail-closed）")
        return 0
    files = sorted(MEASUREMENT_DIR.glob("*.json"))
    if not files:
        print("[feature-measurement] skip: 无测量产物")
        return 0

    fails: list[str] = []
    ancestors = 0
    for fp in files:
        rel = fp.relative_to(REPO).as_posix()
        try:
            d = json.loads(fp.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError) as e:
            fails.append(f"{rel}: 解析失败 {e}")
            continue
        if BANNER_MARK not in str(d.get("_generated_by", "")):
            fails.append(f"{rel}: 缺 AUTO-GENERATED banner（疑手写产物）")
        if not isinstance(d.get("features"), dict):
            fails.append(f"{rel}: features 结构非法")
        if _is_ancestor(d.get("git_sha", "")):
            ancestors += 1

    if fails:
        print(f"[feature-measurement] FAIL: {len(fails)} 项：")
        for f in fails:
            print(f"  {f}")
        return 1
    if ancestors == 0:
        print(f"[feature-measurement] WARN: {len(files)} 份产物无一 git_sha 为 HEAD 祖先"
              "（陈旧/异线，建议跑 scripts/capture_feature_status.py 重采）")
        return 0
    print(f"[feature-measurement] OK: {len(files)} 份产物 schema/banner 合法，{ancestors} 份为 HEAD 祖先")
    return 0


if __name__ == "__main__":
    sys.exit(main())
