#!/usr/bin/env python3
"""gen_feature_status.py — 生成 feature 状态视图（status 现算、不存储）.

单一事实源：status 由 `feature_status_lib.compute_status` 从 SPEC+MEASUREMENT+SIGN-OFF
现算，本脚本只把结果**渲染**成可 diff 的视图 `.testing/status/feature-status.md`
（机器视图住机器真相树 .testing/status/，挨着它渲染的 measurement/）。
视图带 AUTO-GENERATED banner，`--check` 字节相等守卫保证它永不被手改（同 段 29 范式）。

不生成 Wave 滚动标签（用户决策）：按 wave 分组列出每 feature 的计算状态 + 三输入 + 计数；
"是否 shipped" 全 Done 一眼可见，不再靠一个有损的人工汇总词。

Usage:
    ./scripts/gen_feature_status.py            # 生成/刷新视图
    ./scripts/gen_feature_status.py --check     # 校验视图与现算一致（preflight 段 61）
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from feature_status_lib import REPO, compute_all, load_measurement  # noqa: E402

OUT = REPO / ".testing" / "status" / "feature-status.md"
BANNER = (
    "<!-- AUTO-GENERATED by scripts/gen_feature_status.py — DO NOT EDIT BY HAND. -->\n"
    "<!-- 重新生成：python3 scripts/gen_feature_status.py -->\n"
    "<!-- 真值源：.feature(SPEC) + .testing/status/measurement/<sha>.json(MEASUREMENT) "
    "+ .testing/signoff/<scope>.signoff.yaml covers(SIGN-OFF)。status 现算不存储。 -->\n"
)

# wave 目录 → 展示名
WAVE_TITLE = {
    "wave-0-golden-path": "Wave 0 · 机械守卫 + J1 黄金链路",
    "wave-1-j1-j2-closed-loop": "Wave 1 · J1 闭环 + J2 挂数",
    "wave-2-engines-b1-zones": "Wave 2 · 三引擎 + B1 + 共享专区",
    "wave-3-protocol-tenant-national": "Wave 3 · 协议硬化 + 多租户 + 国家通道",
    "wave-4-legacy-retirement": "Wave 4 · legacy 退役",
    "cross": "Cross-cutting · 跨 wave 回归",
}
WAVE_ORDER = list(WAVE_TITLE.keys())


def _axes(r: dict) -> str:
    if r["status"] == "Backlog":
        return f"延期：{r['deferred']}"
    g = "绿" if r["green"] else ("待测" if not r["refs"] else "未绿")
    s = "已签" if r["signed"] else "未签"
    return f"测量={g} / 签字={s}"


def build() -> str:
    rows = compute_all()
    m = load_measurement()
    by_wave: dict[str, list[dict]] = {}
    for r in rows:
        by_wave.setdefault(r["wave"], []).append(r)

    from collections import Counter
    total = Counter(r["status"] for r in rows)

    lines: list[str] = [BANNER, "# Feature 状态（机械生成）\n"]
    lines.append(
        "> status = f(SPEC, MEASUREMENT, SIGN-OFF)，每次 preflight 现算，不手敲、不存第二份。\n"
        "> **Done** = 测试真绿 ∧ 业务签字；**Ready** = 已签未绿；**InTest** = 绿/在测但未签（代码完成待签字）；"
        "**Draft** = 纯意图；**Backlog** = 排期外（`# Deferred:`）。\n"
    )
    cap = (m or {}).get("captured_at", "—")
    green_n = sum(1 for r in rows if r["green"])
    tested_n = sum(1 for r in rows if r["refs"])
    lines.append(
        f"> 测量基线：captured_at=`{cap}` · 指纹新鲜绿 {green_n}/{tested_n}"
        "（信任锚=内容指纹，非 git_sha；squash 免疫，测试/规格变即失效）\n"
    )
    order = ["Done", "Ready", "InTest", "Draft", "Backlog"]
    summary = " / ".join(f"{k} {total.get(k, 0)}" for k in order)
    lines.append(f"> 合计 {len(rows)}：{summary}\n")

    for w in WAVE_ORDER + [k for k in by_wave if k not in WAVE_ORDER]:
        if w not in by_wave:
            continue
        wr = sorted(by_wave[w], key=lambda x: x["rel"])
        wc = Counter(r["status"] for r in wr)
        wsum = " · ".join(f"{k} {wc[k]}" for k in order if wc.get(k))
        lines.append(f"\n## {WAVE_TITLE.get(w, w)}  （{wsum}）\n")
        lines.append("| feature | status | 依据 |")
        lines.append("|---|---|---|")
        for r in wr:
            name = r["rel"].split("/")[-1]
            lines.append(f"| {name} | **{r['status']}** | {_axes(r)} |")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description="生成 feature 状态视图（现算不存储）")
    ap.add_argument("--check", action="store_true", help="校验视图与现算一致（preflight 段 61）")
    args = ap.parse_args()

    content = build()
    if args.check:
        if not OUT.exists():
            print(f"[feature-status-gen] FAIL: 缺生成视图 {OUT.relative_to(REPO)} — 跑 python3 scripts/gen_feature_status.py")
            return 1
        if OUT.read_text(encoding="utf-8") != content:
            print(f"[feature-status-gen] FAIL: {OUT.relative_to(REPO)} 与现算漂移 — 跑 python3 scripts/gen_feature_status.py 重生成")
            return 1
        print(f"[feature-status-gen] OK: {OUT.relative_to(REPO)} 与 SPEC+MEASUREMENT+SIGN-OFF 现算一致")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(content, encoding="utf-8")
    print(f"[feature-status-gen] wrote {OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
