#!/usr/bin/env python3
"""gen_debt_status — render .testing/debt/debt-status.md from compute_statuses.

DO-NOT-EDIT banner is emitted; preflight --check re-renders and diffs to catch
hand edits (debt status is a function of each entry's assert, not a stored list).
Mirrors gen_feature_status.py.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from debt_status_lib import INVALID, OPEN, REPO_ROOT, STALE_FIXED, compute_statuses

BANNER = "<!-- GENERATED BY scripts/gen_debt_status.py — DO NOT EDIT (debt status is a function) -->"
OUT = REPO_ROOT / ".testing" / "debt" / "debt-status.md"
ORDER = (OPEN, STALE_FIXED, INVALID)


def render(statuses) -> str:
    lines = [BANNER, "", "# Preflight Debt Status (computed)", ""]
    if not statuses:
        lines.append("_(no debt entries in .testing/debt/)_")
        return "\n".join(lines).rstrip() + "\n"
    by_state: dict[str, list] = {}
    for st in statuses:
        by_state.setdefault(st.state, []).append(st)
    for state in ORDER:
        items = by_state.get(state, [])
        if not items:
            continue
        lines.append(f"## {state} ({len(items)})")
        for st in sorted(items, key=lambda s: s.slug):
            sev = f" [{st.severity}]" if st.severity else ""
            date = f" ({st.date})" if st.date else ""
            lines.append(f"- {st.slug}{sev}{date} — {st.title}")
            lines.append(f"  - assert: {st.kind} → {st.detail}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    statuses = compute_statuses()
    rendered = render(statuses)
    check = "--check" in sys.argv
    if check:
        if not OUT.exists():
            print(f"[debt-status-gen] MISSING: {OUT}", file=sys.stderr)
            print("  run: python scripts/gen_debt_status.py", file=sys.stderr)
            return 1
        current = OUT.read_text(encoding="utf-8")
        if current != rendered:
            print("[debt-status-gen] DRIFT: .testing/debt/debt-status.md out of date", file=sys.stderr)
            print("  run: python scripts/gen_debt_status.py", file=sys.stderr)
            return 1
        print("[debt-status-gen] OK: .testing/debt/debt-status.md 与各 debt assert 现算一致")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(rendered, encoding="utf-8")
    print(f"[debt-status-gen] wrote {OUT.relative_to(REPO_ROOT)} ({len(statuses)} debt entr(ies))")
    return 0


if __name__ == "__main__":
    sys.exit(main())
