"""L1 entry layer: REST / MCP / A2A boundaries.

WebUI (L1.1) is a separate frontend SPA and does not live in this package.
All four entries share the same Skill contract per D2 — see
`docs/agent_integration.md` (auto-generated by `scripts/export_agent_contract.py`).
"""
