"""L1 entry layer: REST / CLI / MCP / A2A boundaries.

WebUI (L1.1) is a separate frontend SPA and does not live in this package.
K12 dashboard unit retired (详见 D15 二次反转).
All runtime-facing consumer surfaces share the same Skill contract per D2 —
see `docs/agent_integration.md` (auto-generated by
`scripts/export_agent_contract.py`).
"""
